<div class="row-fluid">
<div class="col-lg-12">
    <form name="form-recep" method="post" autocomplete="off" action="">
        <input name="guardar" type="hidden" value="1" />
        <input name="tipo" type="hidden" value="1" />
		<input name="transporte" id="transporte" type="hidden" value="0" />
        <div class="panel panel-default">
            <div class="panel-heading"></div>
            <div class="panel-body">    
                <div class="col-lg-12">
                    <div class="panel panel-default">
                        <div class="panel-body">
                            <div class="form-group col-xs-3">
                                <label>Depósito de Recepción</label>
                                <select name="deposito" id="deposito" class="form-control" required >
                                    <option value="">-Seleccione-</option>
                                    <?php if(isset($this->deposito)): ?>
                                    <?php foreach ($this->deposito as $dep): ?>
                                        <option value="<?php echo $dep['id_deposito'] ?>"><?php echo ucfirst($dep['nombre_deposito']) ?></option>
                                    <?php endforeach; ?>
                                    <?php endif; ?>
                                </select>
                            </div>
                            <div class="form-group col-xs-3">
                                <label>Nro de Despacho</label>
                                <select name="despacho" id="despacho" class="form-control" >
                                    <option value="">-Seleccione-</option>
                                    
                                </select>
                            </div>
                            <div class="form-group col-xs-3">
                                <label>Fecha</label>
                                <input name="fecha_despacho" type="date" class="form-control" id="fecha_despacho"   required disabled="true" >
                            </div>
                            
                            <div class="form-group col-xs-3">
                                <label>Origen Despacho</label>
                                <input name="deposito_origen" type="text" class="form-control" id="deposito_origen"   required  >
                            </div>
                            
                        </div>
                    </div>
                </div>
                <div class="col-lg-12" id="listado">
                    <div class="panel panel-default">
                        <div class="panel-heading">
                            <button class="btn btn-default input-sm"  id="agregar" type="button" disabled="true"><i class="fa fa-plus"></i></button>
                        </div>         
                        <div class="table-responsive">
                            <table class="table table-bordered" id="tabla">
                                <thead>
                                    <tr >
                                        <th width='30'></th>
                                        <th width='150'>Código</th>
                                        <th width='400'>Descripción</th>
                                        <th width='150'>Marca</th>
                                        <th width='250'>Presentacion</th>
                                        <th width='100'>Cantidad</th>
                                        <th></th>

                                    </tr>
                                </thead>
                                <tbody>

                                </tbody>
                            </table>
                        </div>

                    </div>
                 <br/>
                 
                </div>
                <div class="form-inline col-lg-12">
                    <a href="<?php echo BASE_URL ?>transaccion/almacen/recepcionInterna/"><button type="button" class="btn btn-danger"><i class="fa fa-undo"></i> Cancelar</button></a>   
                   <button type="submit" class="btn btn-primary" oninvalid="alert('Llene todos los campos obligatorios ....');"><i <i class="fa fa-floppy-o"></i></i> Guardar</button>

                </div>
            </div>    
        </div>
    </form>
</div> 

<div class="modal fade" id="myModal" data-toggle="modal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <label>Nombre del Producto</label>
        <input name="producto" id="producto" type="text" class="form-control"  />        
      </div>
      <div class="modal-body">
          <input name="id_fila" id="id_fila" type="hidden" class="form-control"  />
          <div class="panel panel-default" >
              <div class="panel-body">
                  <div id="table_concepto">
                      
                  </div>   
              </div>
          </div>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
      </div>
    </div>
  </div>
</div>
</div>