<div class="row">
    <div class="col-lg-12 col-md-6">
        <ul class="nav nav-tabs">
            <li role="presentation" class="active"><a href="#"><i  class="fa fa-cube"></i> Productos</a></li> 
            <li role="presentation"><a href="<?php echo  BASE_URL ?>archivo/servicio/index/"><i  class="fa  fa-wrench"></i> Servicios</a></li>				
	</ul>
	<div class="panel panel-default">
	<div class="">
            <nav class="navbar navbar-default">
		<div class="container-fluid">
                    <div class="navbar-header navbar-btn">
                        <a class="" href="<?php echo BASE_URL ?>almacen/producto/agregar/" ><button class="btn btn-default" type="button"><i class="fa fa-plus"></i></button></a>
                        <a class="" href="<?php echo BASE_URL ?>reporte/index/print_ListaRecepcionProv/"  target="_blank"><button class="btn btn-default" type="button"><i class="fa fa-print"></i></button></a>                                     
                    </div>  
                    <form class="navbar-form navbar-right" role="search" action="" method="post">
                        <div class="form-group">
                            <label>Depósito</label>    
                            <?php if(isset($this->depTrb) && count($this->depTrb)>0): ?>
                            <select name="deposito" id="deposito" class="form-control">   
                                <option value="0">TODOS</option>   
                                <?php foreach($this->depTrb as $dep): ?>
                                <?php if(isset($this->depAct)&& $this->depAct==$dep['id_deposito']): ?>
                                <option value="<?php echo $dep['id_deposito'] ?>" selected="true"><?php echo $dep['nombre_deposito'] ?></option>       
                                <?php else: ?>
                                <option value="<?php echo $dep['id_deposito'] ?>"><?php echo $dep['nombre_deposito'] ?></option>       
                                <?php endif; ?>
                                <?php endforeach; ?>    
                            </select>     
                            <?php endif; ?> 
                            <input type="text" name="busqueda" class="form-control" placeholder="Busqueda">
                        </div>
                        <button type="submit" class="btn btn-default">Enviar</button>
                    </form>    
		</div>
            </nav>
	</div>     
	
                <div class="panel-body">
                    <div class="table-responsive">
                            <table class="table table-bordered">
                                    <thead>
                                            <tr class="cabecera-gris">
                                                    <th width="80">Código</th>
                                                    <th>Nombre</th>
                                                    <th>Presentación</th>
                                                    <th>Marca</th>
                                                    <th>Modelo</th>
                                                    <th width="30"></th>
                                                    <th width="30"></th>
                                            </tr>
                                    </thead>
                                    <tbody>
                                    <?php if(isset($this->producto) && count($this->producto)) :?>
                                            <?php foreach ($this->producto as $val) :?>
                                            <tr>
                                                    <td><?php echo $val['codigo_producto'] ?></td>
                                                    <td><?php echo strtoupper($val['nombre_producto']) ?></td>
                                                    <td><?php echo ucwords($val['presentacion']) ?></td>
                                                    <td><?php echo ucwords($val['marca']) ?></td>
                                                    <td><?php echo ucwords($val['modelo']) ?></td>
                                                    <td width="30" >
                                                            <a href="<?php echo BASE_URL ?>almacen/producto/editar/<?php echo $val['id_det_producto'] ?>" >
                                                            <button class="btn btn-default"><i class="fa fa-pencil-square-o"></i></button>
                                                    </td>
                                                    <td width="30">
                                                        <a href="<?php echo BASE_URL ?>almacen/producto/detalle/<?php echo $val['id_producto'] ?>" ><button class="btn btn-default">
                                                            <i class="fa fa-bars"></i></button>
                                                    </td>
                                            </tr>
                                            <?php endforeach; ?>
                                    <?php endif; ?>    
                                    </tbody>
                            </table>

                    </div>
		</div>
		<div class="panel-footer" >
	            <p>
	                <?php if(isset($this->paginacion)) echo $this->paginacion; ?>
	            </p>
	    	</div>
	</div>        
	</div>
</div>  

<div class="modal fade bs-example-modal-lg" tabindex="-1" role="dialog" aria-labelledby="myLargeModalLabel">
  <div class="modal-dialog modal-lg">
    <div class="modal-content">
      <div class="modal-header cabecera-gris">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
		<h3>Recepción de Productos</h3>
      </div>
      <div class="modal-body">
          <div class="panel-default">
              <div class="panel-body">
                <div class="form-group col-md-3">
                    <label>Nro de Recepción</label>
                    <input name="nro" id="nro" type="text" class="form-control " value="" />
                </div>
                <div class="form-group col-md-3">
                    <label>Fecha</label>
                    <input name="fecha" id="fecha" type="text" class="form-control" value="" />
                </div>
                <div class="form-group col-md-5">
                    <label>Depósito de Recepción</label>
                    <input name="proveedor" id="proveedor" type="text" class="form-control" value="" />
                </div>
              </div>    
          </div>
          <div class="panel-default">
              <div class="panel-body">
                    <div id="tabla-detalle">
                        <div class="table-responsive">
                          <table class="table table-bordered" id="tabla">
                              <thead>
                                  <tr class="cabecera-gris" >
                                      <th width='150'>Código</th>
                                      <th width='400'>Descripción</th>
                                      <th width='150'>Marca</th>
                                      <th width='250'>Presentacion</th>
                                      <th width='100'>Cantidad</th>
                                      <th></th>
                                  </tr>
                              </thead>
                              <tbody>

                              </tbody>
                          </table>
                      </div>
                    </div>
                  <div>
                      <button><i class="fa fa-print"></i></button>
                  </div>
                  </div>
          </div>
      </div>    
    </div>
  </div>
</div>