<?php //print_r($_layoutParams['argumentos']) ?>
<div class="row">
        <div class="col-lg-8 col-md-6">
        <div class="panel panel-default">
        <div class="">
            <nav class="navbar navbar-default">
                <div class="container-fluid">
                    <div class="navbar-header navbar-btn">
			<a > <button class="btn btn-default nuevo" title="Presione aquí para AGREGAR un nuevo registro" value="" ><i  class="fa fa-plus"></i></button> </a>
                    </div>  
                    <form class="navbar-form navbar-right" role="search" action="" method="post">
                        <div class="form-group">
                            <input type="text" maxlength="100" name="busqueda" class="form-control" placeholder="Filtrar nombre">
                        </div>
                        <button type="submit" class="btn btn-default"><i  class="fa fa-search" ></i></button>
                    </form>    
                </div>
            </nav>
        </div>
          <div class="panel-body">
            <div class="table-responsive">
                <table class="table table-bordered">
                    <thead>
                        <tr class="bg-light-blue-active">
                        <th>Código</th>
                        <th>Nombre</th>
                        <th>Comentario</th>
                        <th width="30"></th>
                        <th width="30"></th>
                    </tr>
                    </thead>
                    <tbody>
                    <?php $i = 1; ?>    
                    <?php if(isset($this->lista) && count($this->lista)) :?>
                        <?php foreach ($this->lista as $val) :?>
                        <tr >
                            <td><?php echo $val['id_tipo_gasto'] ?></td>
                            <td><?php echo $val['nombre_tipo_gasto'] ?></td>
                            <td><?php echo $val['comentario_tipo_gasto'] ?></td>
                            <td>
                                <?php if($val['estatus_tipo_gasto']==1): ?>
					<button class="btn btn-default editar" title="Presione aquí para EDITAR" value="<?php echo $val['id_tipo_gasto'] ?>" ><i  class="fa fa-pencil-square-o"></i></button>
                                <?php endif; ?>
                            </td>    
                            <td>
                                <?php if($val['estatus_tipo_gasto']==1): ?>
					<button class="btn btn-default eliminar" title="Presione aquí para ELIMINAR" value="<?php echo $val['id_tipo_gasto'] ?>"><i class="fa fa-trash-o"></i></button>
                                <?php endif; ?>
                            </td>
                        </tr>
                        <?php $i++; ?>
                        <?php endforeach; ?>
                    <?php endif; ?>    
                    </tbody>
                </table>
                <hr>
                <p>
                      <?php if(isset($this->paginacion)) echo $this->paginacion; ?>
                </p>
            </div>
          </div>

        </div>
    </div>
    <div class="col-lg-4 col-md-6">
        <div class="panel panel-default">
            <div class="panel-heading">Gestión de Tipo de Gasto</div>
            <div class="panel-body">
                <form name="tgasto" id="tgasto" method="post" autocomplete="off" action="<?php echo BASE_URL ?>archivo/tipoGasto/agregar/">
                    <input name="guardar" type="hidden" value="1" id="guardar">
                    <input name="id" type="hidden" value="0" id="id">
                    <input name="aux" type="hidden" value="0" id="aux">
                    <div class="form-group">
                      <label>***Nombre:</label>
                      <input name="nombre" maxlength="100" type="text" class="form-control" disabled="true" id="nombre" required placeholder="Ingrese nombre " >
                    </div>
                    <div class="form-group">
                      <label>Comentario:</label>
                      <textarea name="comentario" maxlength="150" cols="1" rows="5" type="text" disabled="true" multiple="1" class="form-control" id="comentario"  placeholder="Ingrese un comentario"></textarea>
                    </div>
                    <button type="button" title="Presione aquí para Guardar el registro" name="agregar" id="agregar" class="btn btn-primary" ><i class="fa fa-floppy-o"></i> Guardar</button>
                    <button type="button" name="cancelar" title="Presione aquí para VACIAR el formulario" id="cancelar" class="btn btn-danger"><i class="fa fa-undo"></i> Cancelar</button>
                </form>    
            </div>
        </div>
    </div>    
</div>
