<div class="col-lg-12">
    <form name="form_agregar" id="form_agregar" method="post" autocomplete="off" action="">    
<div class="panel panel-default">
    <div class="panel-heading">Información Personal</div>
    
    <div class="panel-body">
        <input name="guardar" id="guardar" type="hidden" value="2" /> 
        <input name="id" id="id" type="hidden" value="<?php echo $this->trabajador['id_trabajador'] ?>" /> 
        <div class="form-group ">
            <div class="form-inline">
              <label class="control-label">*** Cédula:</label>
              <select  class="form-control" disabled=""  name="nacionalidad" id="nacionalidad" />
                  <option value="V" <?php if($this->trabajador['nacionalidad_persona'] =='V') echo 'selected' ?>  >V</option>
                  <option value="E" <?php if($this->trabajador['nacionalidad_persona'] =='E') echo 'selected' ?> >E</option>
              </select>
              <input name="cedula" disabled="true" type="text" value="<?php if(isset($this->trabajador['cedula_persona'])) echo $this->trabajador['cedula_persona'] ?>"  class="form-control"  id="cedula" placeholder="" />
             </div>              
        </div>
        
        <hr>   
        <div class="form-group col-xs-6">
            <label>*** Primer Nombre:</label>
            <input name="pri_nombre" maxlength="30" type="text" value="<?php if(isset($this->trabajador['pri_nombre_persona'])) echo $this->trabajador['pri_nombre_persona'] ?>" class="form-control" size="10" id="pri_nombre" placeholder="Ingrese primer nombre" required >
        </div>
        <div class="form-group col-xs-6">
            <label>Segundo Nombre:</label>
            <input name="seg_nombre" maxlength="30" type="text" value="<?php if(isset($this->trabajador['seg_nombre_persona'])) echo $this->trabajador['seg_nombre_persona'] ?>" class="form-control" size="30" id="seg_nombre" placeholder="Ingrese segundo nombre" >
        </div>
        <div class="form-group col-xs-6">
            <label>*** Primer Apellido:</label>
            <input name="pri_apellido" maxlength="30" type="text" value="<?php if(isset($this->trabajador['pri_apellido_persona'])) echo $this->trabajador['pri_apellido_persona'] ?>" class="form-control" size="30" id="pri_apellido" placeholder="Ingrese primer apellido" required >
        </div>
        <div class="form-group col-xs-6">
            <label>Segundo Apellido:</label>
            <input name="seg_apellido" type="text" value="<?php if(isset($this->trabajador['seg_apellido_persona'])) echo $this->trabajador['seg_apellido_persona'] ?>" class="form-control" size="30" id="seg_apellido" placeholder="Ingrese segundo apellido" >
        </div>
        <div class="form-group col-xs-6">
            <label>*** Fecha de Nacimiento:</label>
            <input name="fecha_nac" maxlength="10" type="date" value="<?php if(isset($this->trabajador['fecha_nac_persona'])) echo $this->trabajador['fecha_nac_persona'] ?>" class="form-control" size="30" id="fecha_nacimiento" placeholder="Ej.: 1982-10-20" required > 
        </div>
        <div class="form-group col-xs-6">
            <label>*** Sexo:</label>
            <select class="form-control" name="sexo" id="sexo" required />
                    <option value="-">-Seleccione-</option>
                    <option value="F" <?php if($this->trabajador['sexo_persona'] =='F') echo 'selected' ?> >Femenino</option>
                    <option value="M" <?php if($this->trabajador['sexo_persona'] =='M') echo 'selected' ?> >Masculino</option>
                </select>
        </div>
        <div class="form-group col-xs-6">
            <label>Estado Civil:</label>
                <select class="form-control" name="estado_civil" id="estado_civil" required />
                    <option value="-">-Seleccione-</option>
                    <option value="S" <?php if($this->trabajador['estado_civil_persona'] =='S') echo 'selected' ?> >Soltero(a)</option>
                    <option value="C" <?php if($this->trabajador['estado_civil_persona'] =='C') echo 'selected' ?> >Casado(a)</option>
                    <option value="D" <?php if($this->trabajador['estado_civil_persona'] =='D') echo 'selected' ?> >Divorciado(a)</option>
                    <option value="V" <?php if($this->trabajador['estado_civil_persona'] =='V') echo 'selected' ?> >Viudo(a)</option>
                </select>
        </div>
        <div class="form-group col-xs-6">
            <label>Lugar de Nacimiento:</label>
            <input name="lugar_nac" type="text" value="<?php if(isset($this->trabajador['lugar_nac_persona'])) echo $this->trabajador['lugar_nac_persona'] ?>" class="form-control" size="70" id="lugar_nac" placeholder="Ingrese lugar de nacimiento"  >
        </div>
    </div>
</div>        

<div class="panel panel-default">
    <div class="panel-heading">Datos de Referencia</div>
    <div class="panel-body">
        <div class="form-group col-xs-6">
            <label>*** Estado:</label>
            <select class="form-control" name="estado" id="estado" required />
                <option value="-">-Seleccione-</option>
                <?php if(isset($this->esta) && count($this->esta)):  ?>
                <?php foreach($this->esta as $val): ?>
                    <?php if($val['id_estado']== $this->trabajador['estado_id']): ?>
                        <option value="<?php echo $val['id_estado']  ?>" selected><?php echo $val['descripcion_estado'] ?></option>
                    <?php else: ?>
                        <option value="<?php echo $val['id_estado']  ?>" ><?php echo $val['descripcion_estado'] ?></option>
                    <?php endif; ?>
                <?php endforeach; ?>
                <?php endif; ?>
            </select>
        </div>
        <div class="form-group col-xs-6">
            <label>*** Municipio:</label>
            <select class="form-control" name="municipio" id="municipio" required />
                <option value="-">-Seleccione-</option>
                <?php if(isset($this->muni) && count($this->muni)):  ?>
                <?php foreach($this->muni as $val): ?>
                    <?php if($val['id_municipio']== $this->trabajador['municipio_id']): ?>
                        <option value="<?php echo $val['id_municipio']  ?>" selected><?php echo $val['descripcion_municipio'] ?></option>
                    <?php else: ?>
                        <option value="<?php echo $val['id_municipio']  ?>" ><?php echo $val['descripcion_municipio'] ?></option>
                    <?php endif; ?>
                <?php endforeach; ?>
                <?php endif; ?>
            </select>
        </div>
        <div class="form-group col-xs-6">
            <label>*** Parroquia:</label>
            <select class="form-control" name="parroquia" id="parroquia" required />
             <option value="-">-Seleccione-</option>
             <?php if(isset($this->parr) && count($this->parr)):  ?>
             <?php foreach($this->parr as $val): ?>
                <?php if($val['id_parroquia']== $this->trabajador['parroquia_id']): ?>
                    <option value="<?php echo $val['id_parroquia']  ?>" selected><?php echo $val['descripcion_parroquia'] ?></option>
                <?php else: ?>
                    <option value="<?php echo $val['id_parroquia']  ?>" ><?php echo $val['descripcion_parroquia'] ?></option>
                <?php endif; ?>
             <?php endforeach; ?>
             <?php endif; ?>
            </select>
        </div>
        <div class="form-group col-xs-6">
            <label>*** Sector:</label>
            <select class="form-control" name="sector" id="sector" required />
             <option value="-">-Seleccione-</option>
             <?php if(isset($this->sect) && count($this->sect)):  ?>
             <?php foreach($this->sect as $val): ?>
                <?php if($val['id_sector']== $this->trabajador['sector_id']): ?>
                    <option value="<?php echo $val['id_sector']  ?>" selected><?php echo $val['descripcion_sector'] ?></option>
                <?php else: ?>
                    <option value="<?php echo $val['id_sector']  ?>" ><?php echo $val['descripcion_sector'] ?></option>
                <?php endif; ?>
             <?php endforeach; ?>
             <?php endif; ?>
            </select>
        </div>
        <div class="form-group col-xs-6">
            <label>*** Dirección de Domicilio:</label>
            <input name="direccion" maxlength="100" required type="text" value="<?php if(isset($this->trabajador['direccion_persona'])) echo $this->trabajador['direccion_persona']; ?>" class="form-control" id="direccion" placeholder="Ingrese dirección de domicilio" size="70" >
        </div>
        <div class="form-group col-xs-6">
            <label>Teléfono Movil:</label>
            <input name="celular" maxlength="11" type="text" value="<?php if(isset($this->trabajador['celular_persona'])) echo $this->trabajador['celular_persona'] ?>" class="form-control" size="70" id="celular" placeholder="Ej.: 04141592306" >
        </div>
        <div class="form-group col-xs-6">
            <label>Teléfono Local:</label>
            <input type="text" class="form-control" value="<?php if(isset($this->trabajador['telefono_persona'])) echo $this->trabajador['telefono_persona'] ?>" name="local" id="local" placeholder="Ej.: 02552569856" />
        </div>
        <div class="form-group col-xs-6">
            <label>*** Correo Electrónico:</label>
            <input type="email" class="form-control" required value="<?php if(isset($this->trabajador['correo_trabajador'])) echo $this->trabajador['correo_trabajador'] ?>" name="correo" id="correo" placeholder="Ej.: micorreo@hotmail.com"  />
        </div>
		<div class="form-group col-xs-6">
            <label>Nº Licencia de Conducir:</label>
            <input name="licencia" maxlength="12"  type="text" value="<?php if(isset($this->trabajador['licencia_persona'])) echo $this->trabajador['licencia_persona'] ?>" class="form-control" id="licencia" placeholder="Ingrese número de licencia para conducir"  >  
        </div>
    </div>
</div>

<div class="panel panel-default">
    <div class="panel-heading">Información Laboral:</div>
    <div class="panel-body">
        <div class="form-group col-xs-6">
            <label>***Departamanto:</label>
            <select class="form-control" name="dpto" id="dpto" required />
                <option value="-">-Seleccione-</option>
                <?php if(isset($this->dpto) && count($this->dpto)):  ?>
                <?php foreach($this->dpto as $val): ?>
                   <?php if($val['id_cargo']== $this->trabajador['cargo_id']): ?>
                       <option value="<?php echo $val['id_cargo']  ?>" selected><?php echo  utf8_decode($val['descripcion_departamento']) ?></option>
                   <?php else: ?>
                       <option value="<?php echo $val['id_cargo']  ?>" ><?php echo $val['descripcion_departamento'] ?></option>
                   <?php endif; ?>                     
                <?php endforeach; ?>
                <?php endif; ?>
            </select>
        </div>
		<div class="form-group col-xs-6">
            <label>*** Cargo:</label>
            <select class="form-control" name="cargo" id="cargo" required />
                <option value="-">-Seleccione-</option>
                <?php if(isset($this->tipo) && count($this->tipo)):  ?>
                <?php foreach($this->tipo as $val): ?>
                   <?php if($val['id_cargo']== $this->trabajador['cargo_id']): ?>
                       <option value="<?php echo $val['id_cargo']  ?>" selected><?php echo utf8_decode($val['nombre_cargo']) ?></option>
                   <?php else: ?>
                       <option value="<?php echo $val['id_cargo']  ?>" ><?php echo utf8_decode($val['nombre_cargo']) ?></option>
                   <?php endif; ?>                     
                <?php endforeach; ?>
                <?php endif; ?>
            </select>
        </div>
		<div class="form-group col-xs-6">
            <label>Fecha de Ingreso:</label>
            <input name="licencia" maxlength="12"  type="text" value="<?php if(isset($this->trabajador['licencia_persona'])) echo $this->trabajador['licencia_persona'] ?>" class="form-control" id="licencia" placeholder="Ingrese número de licencia para conducir"  >  
        </div>
        <div class="form-group col-xs-6">
            <label>Condicion Actual:</label>
            <select name="condicion" class="form-control" id="condicion">
				<option value="activo">ACTIVO</option>
				<option value="inactivo">INACTIVO</option>
			</select>
        </div>
		
    </div>
</div>
       


</div>
    <br/>
        <a href="<?php echo BASE_URL ?>archivo/trabajador/index">
        <button type="button" title="Presione aquí para SALIR de la Edición" class="btn btn-danger"><i class="fa fa-undo"></i>Cancelar</button>
        </a>
        <button type="submit" name="agregar" id="agregar" title="Presione aquí para Guardar" class="btn btn-primary" ><i class="fa fa-floppy-o"></i>Guardar</button>
        <button type="button" name="limpiar" id="limpiar" title="Presione aquí para REINICIAR el formulario" class="btn btn-danger">Limpiar</button>
        <button type="button" name="restaurar" id="restaurar" title="Presione aquí para RESTAURAR DATOS del formulario" class="btn btn-danger">Restaurar Datos</button>
    <br/>
    <br/>
</form>
</div>
