<div class="row">
    <div class="col-lg-12 col-md-6">
        <div class="panel panel-default">
            <div class="">
            <nav class="navbar navbar-default">
                <div class="container-fluid">
                    <div class="navbar-header navbar-btn">
                        <a class="" href="<?php echo BASE_URL ?>rrhh/trabajador/agregar/" title="Agregar Nuevo Trabajador"><button class="btn btn-default"><i class="fa fa-plus"></i></button></a>
                    </div>  
                    <form class="navbar-form navbar-right" role="search" action="" method="post">
                        <div class="form-group">
                            <input type="text" name="busqueda" class="form-control" placeholder="Filtrar nombre y/o apellido">
                        </div>
                        <button type="submit" class="btn btn-default"><i  class="fa fa-search" > Buscar</i></button>
                    </form>    
                </div>
            </nav>
            </div>
          <div class="panel-body">
            <div class="table-responsive">
                <table class="table table-hover">
                    <thead>
                    <tr>
                        <th>Cédula</th>
                        <th>Nombre(s)</th>
                        <th>Apellido(s)</th>
                        <th>Departamento</th>
                        <th>Cargo</th>
                        <th>Teléfonos</th>
                        <th>Estatus</th>
                        <th></th>
                        <th></th>
                    </tr>
                    </thead>
                    <tbody>
                    <?php if(isset($this->lista) && count($this->lista)) :?>                        
                        <?php foreach ($this->lista as $val) :?>
                        <tr>
                            <td><?php echo $val['nacionalidad_persona'].'-'.$val['cedula_persona'] ?></td>
                            <td><?php echo ucfirst($val['pri_nombre_persona']).' '.ucfirst($val['seg_nombre_persona']) ?></td>
                            <td><?php echo ucfirst($val['pri_apellido_persona']).' '.ucfirst($val['seg_apellido_persona']) ?></td>
                            <td><?php echo $val['cb_depar'] ?></td>
                            <td><?php echo $val['cb_cargo'] ?></td>
                            <td><?php echo $val['telefono_persona'].'/'.$val['celular_persona'] ?></td>
                            <td><?php echo ($val['estatus_trabajador']==1)?'Activo':'Inactivo' ?></td>
                            <td>
                                <a href="<?php echo BASE_URL ?>rrhh/trabajador/editar/<?php echo $val['id_trabajador'] ?>" >
                                <button class="btn btn-default" title="Presione aquí para EDITAR"><i class="fa fa-pencil-square-o"></i></button>
                            </td>
                            <td>
                                <?php if($val['estatus_trabajador']==1): ?>
                                <button class="eliminar btn btn-default" title="Presione aquí para ELIMINAR" value="<?php echo $val['id_trabajador'] ?>"><i class="fa fa-trash-o"></i></button>
                                <?php endif; ?>
                            </td>
                        </tr>
                        <?php endforeach; ?>
                    <?php endif; ?>    
                    </tbody>
                </table>
                <hr>
                <p>
                        <?php if(isset($this->paginacion)) echo $this->paginacion; ?>
                </p>
            </div>
          </div>

        </div>
    </div>
        
</div>