<div class="row">
    <div class="col-lg-12 col-md-6">
        <ul class="nav nav-tabs">
            <li role="presentation" class="active"><a href="#">Solicitud a Proveedores</a></li>
            <li role="presentation"><a href="<?php echo  BASE_URL ?>almacen/recepcion/recepcionInterna/">Registro Presupuesto</a></li>
            <li role="presentation"><a href="<?php echo  BASE_URL ?>almacen/recepcion/recepcionInterna/">Analisis Presupuestario</a></li>
        </ul>
        <div class="panel panel-default">
           <div class="">
                <nav class="navbar navbar-default">
                    <div class="container-fluid">
                        <div class="navbar-header navbar-btn">
                            <a  href="<?php echo BASE_URL ?>compra/cotizacion/agregar/" ><button class="btn btn-default"><i class="fa fa-plus"></i></button></a>
                            <a  target="_blank" href="<?php echo BASE_URL ?>reporte/index/catOrdCompra/" title="Imprimir Lista de Ordenes de Compra"><button class="btn btn-default"><i class="fa fa-print"></i></button></a>
                        </div>  
                        <form class="navbar-form navbar-right" role="search" action="" method="post">
                            <div class="form-group">
                                <input type="text" name="busqueda" class="form-control alfa_desc" placeholder="Filtrar nombre y/o apellido">
                            </div>
                            <button type="submit" class="btn btn-default"><i  class="fa fa-search" > Buscar</i></button>
                        </form>    
                    </div>
                </nav>
            </div>
            <div class="panel-body">
                <div class="table-responsive">
                    <table class="table table-bordered">
                        <thead>
                            <tr class="bg-light-blue-active">
                                <th width="80"">Origen</th>
                                <th width="60">Nro</th>                               
                                <th width="90">Fecha</th>
                                <th width="90">Prioridad</th>
				<th width="80">Plazo</th>
                                <th width="220">Solicitante</th>
                                <th width="220">Destino</th>                                
				<th width="30"></th>
                                <th width="30"></th>
                                <th width="30"></th>
                            </tr>
                        </thead>
                        <tbody>
                        <?php if(isset($this->cotizacion) && count($this->cotizacion)) :?>
                            <?php foreach ($this->cotizacion as $val) :?>
                            <tr>
                                <td><?php echo $val['origen'] ?></td>
                                <td><?php echo $val['id'] ?></td>
				<td><?php echo date('d-m-Y',strtotime($val['fecha'])) ?></td>
                                <td><?php echo strtoupper($val['prioridad']) ?></td>
                                <td class="text-right"><?php echo $val['plazo'] ?></td>                                
                                <td><?php echo strtoupper($val['solicitante']) ?></td>
                                <td><?php echo strtoupper($val['destino']) ?></td>
                                
				<td><button type="button" class="editar btn btn-default" data-toggle="modal" data-target=".bs-example-modal-lg"  data-id="<?php echo $val['id_orden_compra'] ?>"  ><i class="fa fa-search"></i></button></td>
                                <td>
                                    
                                    <a href="<?php echo BASE_URL ?>compra/ordencompra/editar/<?php echo $val['id_orden_compra'] ?>"  >
                                    <button class="editar btn btn-default" title="Presione aquí para EDITAR" value="<?php echo $val['id_orden_compra'] ?>" ><i  class="fa fa-pencil-square-o"></i></button>
                                   
                                </td>
                                <td>  
                                   
                                        <button class="eliminar btn btn-default" title="Presione aquí para ELIMINAR" value="<?php echo $val['id_orden_compra'] ?>" ><i class="fa fa-trash-o"></i></button>
                                   
                                       
                                   
                                </td>
                            </tr>
                            <?php endforeach; ?>
                        <?php endif; ?>    
                        </tbody>
                    </table>
                                
                </div>
            </div>                
            <div class="panel-footer" >
                <p>
                    <?php if(isset($this->paginacion)) echo $this->paginacion; ?>
                </p>
            </div>
        </div>    
    </div>        
</div>
<div class="modal fade bs-example-modal-lg" tabindex="-1" role="dialog" aria-labelledby="myLargeModalLabel">
  <div class="modal-dialog modal-lg">
    <div class="modal-content">
      <div class="modal-header ">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
	<h3>Solicitud de Cotizacion</h3>
      </div>
      <div class="modal-body">
          <div class="panel-default">
              <div class="panel-body">
                <div class="form-group col-md-4">
                    <label>Unidad Operativa</label>
                    <input name="unidad" id="unidad" type="text" class="form-control " value="" />
                </div>
                <div class="form-group col-md-4">
                    <label>Departamento</label>
                    <input name="departamento" id="departamento" type="text" class="form-control " value="" />
                </div>
                <div class="form-group col-md-4">
                    <label>Deposito</label>
                    <input name="deposito" id="deposito" type="text" class="form-control " value="" />
                </div>  
                <div class="form-group col-md-2">
                    <label>Codigo</label>
                    <input name="nro" id="nro" type="text" class="form-control " value="" />
                </div>
                <div class="form-group col-md-2">
                    <label>Fecha</label>
                    <input name="fecha" id="fecha" type="date" class="form-control" value="" />
                </div>
                
                <div class="form-group col-md-2">
                    <label>Prioridad</label>
                    <input name="origen" id="origen" type="text" class="form-control" value="" />
                </div>  
                <div class="form-group col-md-2">
                    <label>Plazo</label>
                    <input name="origen" id="origen" type="text" class="form-control" value="" />
                </div>  
                <div class="form-group col-md-4">
                    <label>Solicitante</label>
                    <input name="solicitante" id="solicitante" type="text" class="form-control" value="" />
                </div>
                <div class="form-group col-md-6">
                    <label>Objetivo</label>
                    <input name="objetivo" id="objetivo" type="text" class="form-control" value="" />
                </div>
                <div class="form-group col-md-6">
                    <label>Comentario</label>
                    <input name="comentario" id="comentario" type="text" class="form-control" value="" />
                </div>  
              </div>    
          </div>
          <div class="panel-default">
              <div class="panel-body">
                    <div id="tabla-detalle">
                        <div class="table-responsive">
                          <table class="table table-bordered" id="tabla">
                              <thead>
                                  <tr class="bg-light-blue-active" >
                                      <th width='150'>Código</th>
                                      <th width='400'>Descripción</th>
                                      <th width='100'>Precio</th>
                                      <th width='100'>Cantidad</th>
                                      <th width='100'>Monto</th>
                                      <th width='100'>Tsa. Iva</th>
                                      <th width='100'>Total</th>
                                  </tr>
                              </thead>
                              <tbody>

                              </tbody>
                          </table>
                      </div>
                    </div>
                  <div>
                        <div>
                            <h4 style="margin-bottom:0px;margin-top:10px;padding:0px;">Totales</h4>
                            <hr style="margin:0px;margin-bottom:8px;">
                            <div class="form-inline" >
                                <div class="form-group">
                                        <label style="margin-left:25px">Sub total</label>
                                        <input type="text" name="subtotal" id="subtotal" class="form-control text-right" value="0" readonly="true" />
                                </div>
                                <div class="form-group">
                                        <label style="margin-left:25px">Total Iva</label>
                                        <input type="text" name="iva" id="iva" class="form-control text-right" value="0" readonly="true" />
                                </div>
                                <div class="form-group">
                                        <label style="margin-left:25px">Total</label>
                                        <input type="text" name="total" id="total" class="form-control text-right" value="0" readonly="true" />
                                </div>
                            </div>
                            <hr />
                        </div>	
                      <div id="enlace"></div>
                  </div>
                  </div>
          </div>
      </div>    
    </div>
  </div>
</div>