<div class="col-lg-12">
<form name="form-menu" method="post" autocomplete="off" action="">    
<div class="panel panel-default">
    <div class="panel-heading">Datos Proveedor</div>
    <div class="panel-body">
          <input name="guardar" type="hidden" value="1" />
          <input name="id" type="hidden" value="<?php echo $this->proveedor['id_proveedor'] ?>" />
          <div class="form-group ">
            <div class="form-inline">
              <label class="control-label">Rif</label>
              <select class="form-control" name="nacionalidad" id="nacionalidad" />
                  <option value="V">V</option>
                  <option value="J">J</option>
                  <option value="G">G</option>
              </select>
              <input name="rif" type="text" class="form-control"  id="rif" placeholder="" required />
             </div>
          </div>
            
            <hr>
          <div class="form-group col-xs-6">
            <label>Razon Social</label>
            <input name="razon_social" type="text" class="form-control" size="70" id="razon_social" placeholder="Primer nombre" >            
          </div>
          <div class="form-group col-xs-6">
            <label>Direccion Fiscal</label>
            <input name="direccion_fiscal" type="text" class="form-control" id="direccion_fiscal" placeholder="" size="70" >  
          </div>
          <div class="form-group col-xs-6">
            <label>Telefono</label>
            <input type="text" class="form-control" name="telefono" id="telefono"  />
          </div>
          <div class="form-group col-xs-6">
            <label>Correo Electronico</label>
            <input type="email" class="form-control" name="correo" id="correo" placeholder=""  />
          </div>
          
    </div>
  </div>        
          <div class="panel panel-default">
          <div class="panel-heading">Informacion Adicional</div>
          <div class="panel-body">
              <div class="form-group col-xs-4">
                <label>Tipo</label>
                <select class="form-control" name="tipo" id="tipo" required />
                    <option value="-">-Seleccione-</option>
                    <?php if(isset($this->tipo) && count($this->tipo)):  ?>
                    <?php foreach($this->tipo as $val): ?>
                        <option value="<?php echo $val['id_tipo_proveedor']  ?>"><?php echo $val['nombre_tipo_proveedor'] ?></option>
                    <?php endforeach; ?>
                    <?php endif; ?>
                </select>
              </div>
              <div class="form-group col-xs-4">
                <label>Contacto</label>
                <input name="contacto" type="text" class="form-control" id="contacto" required placeholder=""  />
              </div>
              
              <div class="form-group col-xs-4">
                <label>Telefono contacto</label>
                <input name="tlf_contacto" type="text" class="form-control" id="tlf_contacto" required />
              </div>
            
          </div>
          </div>
          
          
          </div>
          <br/>
          
          <a href="<?php echo BASE_URL ?>archivo/proveedor/index"><button type="button" class="btn btn-danger"><i class="fa fa-undo"></i> Cancelar</button></a>
          <button type="submit" class="btn btn-primary" oninvalid="alert('Llene todos los campos obligatorios ....');"><i class="fa fa-floppy-o"></i> Guardar</button>
          <br/>
          <br/>
        </form>
    
</div>
