<div class="row">
    <div class="col-lg-12 col-md-6">
        <div class="panel panel-default">
        <div class="">
            <nav class="navbar navbar-default">
                <div class="container-fluid">
                    <div class="navbar-header">
                       <a class="navbar-brand" href="<?php echo BASE_URL ?>archivo/transporte/agregar/" title="Agregar Nuevo Transporte"><i class="fa fa-plus"></i></a>  
                    </div>  
                    <form class="navbar-form navbar-right" role="search" action="" method="post">
                        <div class="form-group">
                            <input type="text" name="busqueda" class="form-control" placeholder="Filtrar tipo de transporte" />
                        </div>
                        <button type="submit" class="btn btn-default"><i  class="fa fa-search" > Buscar</i></button>
                    </form>    
                </div>
            </nav>
        </div>
         
          <div class="panel-body">
            <div class="table-responsive">
                <table class="table table-hover">
                    <thead>
                    <tr>
                        <th>Código</th>
                        <th>Tipo</th>
                        <th>Marca</th>
                        <th>Modelo</th>
                        <th>Placa</th>
                        <th>Capacidad</th>
                        <th>Condición</th>
                        <th>Estatus</th>
                        <th></th>
                        <th></th>
                    </tr>
                    </thead>
                    <tbody>
                    <?php if(isset($this->lista) && count($this->lista)) :?>
                        <?php foreach ($this->lista as $val) :?>
                        <tr>
                            <td><?php echo ucfirst($val['id_transporte']) ?></td>
                            <td><?php echo ucfirst($val['tipo_transporte']) ?></td>
                            <td><?php echo ucfirst($val['marca_transporte']) ?></td>
                            <td><?php echo $val['modelo'] ?></td>
                            <td><?php echo $val['placa'] ?></td>
                            <td><?php echo $val['capacidad']." ".$val['unidad'] ?></td>
                            <td><?php echo $val['condicion_transporte'] ?></td>
                            <td><?php echo ($val['estatus_transporte']==1)?'Activo':'Inactivo' ?></td>
                            <td>
                                <?php if($val['estatus_transporte']==1): ?>
                                <a href="<?php echo BASE_URL ?>archivo/transporte/editar/<?php echo $val['id_transporte'] ?>" >
                                <button class="editar" title="Presione aquí para EDITAR" value="<?php echo $val['id_transporte'] ?>" ><i  class="fa fa-pencil-square-o"></i></button>
                                <?php endif; ?>
                            </td>
                            <td>
                                <?php if($val['estatus_transporte']==1): ?>
                                <button class="eliminar" title="Presione aquí para ELIMINAR" value="<?php echo $val['id_transporte'] ?>" ><i class="fa fa-trash-o"></i></button>
                                <?php endif; ?>
                            </td>
                            
                        </tr>
                        <?php endforeach; ?>
                    <?php endif; ?>    
                    </tbody>
                </table>
                <hr>
                <p>
                        <?php if(isset($this->paginacion)) echo $this->paginacion; ?>
                </p>
            </div>
          </div>

        </div>
    </div>
        
</div>