<div class="row">
        <div class="col-lg-8 col-md-6">
        <div class="panel panel-default">
        <div class="">
        <nav class="navbar navbar-default">
            <div class="container-fluid">
                <div class="navbar-header navbar-btn">
                    <a class=""> <button class="nuevo btn btn-default" title="Presione aquí para AGREGAR un nuevo registro" value="" ><i  class="fa fa-plus"></i></button> </a>
                </div>  
                <form class="navbar-form navbar-right" role="search" action="" method="post">
                    <div class="form-group">
                        <input type="text" maxlength="150" name="busqueda" class="form-control alfa_desc" placeholder="Filtrar pregunta">
                    </div>
                    <button type="submit" class="btn btn-default"><i  class="fa fa-search" ></i></button>
                </form>    
            </div>
        </nav>
            </div>
          <div class="panel-body">
            <div class="table-responsive">
                <table class="table table-bordered">
                    <thead>
                    <tr class="bg-light-blue-active" >
                        <th>Código</th>
                        <th>Descripción</th>
                        <th width="30"></th>
                        <th width="30"></th>
                    </tr>
                    </thead>
                    <tbody>
                    <?php $i = 1; ?>    
                    <?php if(isset($this->lista) && count($this->lista)) :?>
                        <?php foreach ($this->lista as $val) :?>
                        <tr>
                            <td><?php echo $val['id_pregunta'] ?></td>
                            <td><?php echo ucwords($val['pregunta']) ?></td>
                            <td>
                                <?php if($val['estatus_pregunta']==1): ?>
                                <button class="editar btn btn-default" title="Presione aquí para EDITAR" value="<?php echo $val['id_pregunta'] ?>" ><i  class="fa fa-pencil-square-o"></i></button>
                                <?php endif; ?>
                            </td>    
                            <td>
                                <?php if($val['estatus_pregunta']==1): ?>
                                <button class="eliminar btn btn-default" title="Presione aquí para ELIMINAR" value="<?php echo $val['id_pregunta'] ?>"><i class="fa fa-trash-o"></i></button>
                                <?php endif; ?>
                            </td>
                        </tr>
                        <?php $i++; ?>
                        <?php endforeach; ?>
                    <?php endif; ?>    
                    </tbody>
                </table>
                <hr>
                <p>
                      <?php if(isset($this->paginacion)) echo $this->paginacion; ?>
                </p>
            </div>
          </div>

        </div>
    </div>
    <div class="col-lg-4 col-md-6">
        <div class="panel panel-default">
            <div class="panel-heading">Gestión de Pregunta</div>
            <div class="panel-body">
                <form name="form_pregunta" id="form_pregunta" method="post" autocomplete="off" action="<?php echo BASE_URL ?>seguridad/pregunta/agregar/">
                    <input name="guardar" type="hidden" value="1" id="guardar">
                    <input name="id" type="hidden" value="0" id="id">
                    <input name="aux" type="hidden" value="0" id="aux">
                    <div class="form-group">
                      <label>Descripción:</label>
                      <input name="descripcion" disabled="disabled" maxlength="150" type="text" class="form-control alfa_desc" id="descripcion" placeholder="Ingrese descripción de la pregunta" required>
                    </div>
                    <button type="button" disabled="disabled" name="agregar" id="agregar" title="Presione aquí para GUARDAR el registro"  class="btn btn-primary"> <i class="fa fa-floppy-o"></i> Guardar</button>
                    <button type="button" disabled="disabled" name="cancelar" title="Presione aquí para CANCELAR el registro" id="cancelar" class="btn btn-danger"> <i class="fa fa-undo"></i> Cancelar</button>
                  </form>    
            </div>
        </div>
    </div>    
</div>
