<div class="row">
    <div class="col-lg-12 col-md-6">
        <div class="panel panel-default">
            <div class="">
                <nav class="navbar navbar-default">
                    <div class="container-fluid">
                        <div class="navbar-header">
                            <a href="<?php echo BASE_URL ?>venta/cliente/agregar/" title="Agregar nuevo registro"><button class="btn btn-default navbar-btn"><i class="fa fa-plus"></i></button></a>
                        </div>  
                        <form class="navbar-form navbar-right" role="search" action="" method="post">
                            <div class="form-group">
                                <input type="text" name="busqueda" class="form-control" placeholder="Filtrar Razon Social">
                            </div>
                            <button type="submit" class="btn btn-default"><i  class="fa fa-search" > Buscar</i></button>
                        </form>    
                    </div>
                </nav>
            </div>
          <div class="panel-body">
            <div class="table-responsive">
                <table class="table table-bordered">
                    <thead>
                    <tr class="bg-teal-active">
                        <th width="120">Rif</th>
                        <th width="320">Razon Social</th>
                        <th width="450">Direccion Fiscal</th>
                        <th width="220">Correo Electronico</th>
                        <th width="120">Telefono</th>
                        <th width="50">Estatus</th>
                        <th width="20"></th>
						<th width="20"></th>
						
                    </tr>
                    </thead>
                    <tbody>
                    <?php if(isset($this->lista) && count($this->lista)) :?>
                        <?php foreach ($this->lista as $val) :?>
                        <tr>
                            <td><?php echo $val['rif_cliente'] ?></td>
                            <td><?php echo ucfirst($val['razon_social_cliente']) ?></td>
                            <td><?php echo ucfirst($val['direccion_fiscal_cliente']) ?></td>
                            <td><?php echo $val['correo_cliente'] ?></td>
                            <td><?php echo $val['telefono_cliente'] ?></td>
                            <td><?php echo ($val['estatus_cliente']==1)?'Activo':'Inactivo' ?></td>
                            
                            <td><a href="<?php echo BASE_URL ?>venta/cliente/editar/<?php echo $val['id_cliente'] ?>" ><button class="btn btn-default"><i class="fa fa-pencil-square-o"></i></button></td>
                            <td>
                            	<?php if($val['estatus_cliente']==1): ?>
                                <button class="eliminar btn btn-default" title="Presione aquí para ELIMINAR" value="<?php echo $val['id_cliente'] ?>"><i class="fa fa-trash-o"></i></button>
                                <?php endif; ?>
                            </td>
                          
                        </tr>
                        <?php endforeach; ?>
                    <?php endif; ?>    
                    </tbody>
                </table>
              
                <p>
                        <?php if(isset($this->paginacion)) echo $this->paginacion; ?>
                </p>
            </div>
          </div>

        </div>
    </div>
        
</div>