<?php //print_r($_layoutParams['argumentos']) ?>
<div class="row">
        <div class="col-lg-8 col-md-6">
		<ul class="nav nav-tabs">
			<li role="presentation" ><a href="<?php echo BASE_URL ?>venta/cliente/detalle/<?php echo $this->cliente ?>">Analisis Comercial</a></li>
			<li role="presentation" class="active"><a href="#">Premisas de Venta</a></li>
					
		</ul>
        <div class="panel panel-default">
        <div class="">
            <nav class="navbar navbar-default">
                <div class="container-fluid">
                    <div class="navbar-header">
						<a class="navbar-brand"> <button class="nuevo" title="Presione aquí para AGREGAR un nuevo registro" value="" ><i  class="fa fa-plus"></i></button> </a>
                        <a class="navbar-brand" target="_blank" href="<?php echo BASE_URL ?>reporte/index/catRubrosProd/" title="Imprimir Catálogo"><button><i class="fa fa-print"></i></button></a>
                    </div>  
                    <form class="navbar-form navbar-right" role="search" action="" method="post">
                        <div class="form-group">
                            <input type="text" maxlength="100" name="busqueda" class="form-control" placeholder="Filtrar nombre">
                        </div>
                        <button type="submit" class="btn btn-default"><i  class="fa fa-search" > Buscar</i></button>
                    </form>    
                </div>
            </nav>
        </div>
          <div class="panel-body">
            <div class="table-responsive">
                <table class="table table-bordered">
                    <thead>
                    <tr>
                        <th width="90">Código</th>
                        <th>Nombre</th>
                        <th>Accion</th>
                        <th>Porcentaje</th>
                        <th width="30"></th>
                        <th width="30"></th>
                    </tr>
                    </thead>
                    <tbody>
                    <?php $i = 1; ?>    
                    <?php if(isset($this->lista) && count($this->lista)) :?>
                        <?php foreach ($this->lista as $val) :?>
                        <tr >
                            <td><?php echo $val['id_premisa'] ?></td>
                            <td><?php echo $val['nombre_premisa'] ?></td>
                            <td><?php echo $val['accion_premisa'] ?></td>
                            <td><?php echo $val['porcentaje_premisa'] ?></td>
                            <td>
                                <?php if($val['estatus_det_cliente']==1): ?>
                                <button class="editar" title="Presione aquí para EDITAR" value="<?php echo $val['id_det_cliente'] ?>" ><i  class="fa fa-pencil-square-o"></i></button>
                                <?php endif; ?>
                            </td>    
                            <td>
                                <?php if($val['estatus_det_cliente']==1): ?>
                                <button class="eliminar" title="Presione aquí para ELIMINAR" value="<?php echo $val['id_det_cliente'] ?>"><i class="fa fa-trash-o"></i></button>
                                <?php endif; ?>
                            </td>
                        </tr>
                        <?php $i++; ?>
                        <?php endforeach; ?>
                    <?php endif; ?>    
                    </tbody>
                </table>
                
            </div>
          </div>
		  <div class="panel-footer" >
            <p>
                <?php if(isset($this->paginacion)) echo $this->paginacion; ?>
            </p>
    	  </div>	
        </div>
    </div>
    <div class="col-lg-4 col-md-6">
        <div class="panel panel-default">
            <div class="panel-heading">Agregar premisa</div>
            <div class="panel-body">
                <form name="form-premisa" id="form-premisa" method="post" autocomplete="off" action="">
                    <input name="guardar" type="hidden" value="1" id="guardar">
                    <input name="id" type="hidden" value="0" id="id">
                    <input name="cliente" type="hidden" value="<?php echo $this->cliente ?>" id="cliente">
                    <div class="form-group">
                      <label>Premisa:</label>
                      <select name="premisa" id="premisa" class="form-control" disabled="true"> 
					  <option value="">-Seleccione-</option>
					  <?php if(isset($this->premisa) and count($this->premisa)): ?>
					  <?php foreach($this->premisa as $val):?>
						<option value="<?php echo $val['id_premisa'] ?>"><?php echo $val['nombre_premisa'] . ' =>'. $val['porcentaje_premisa'].' %' ?></option>	
					  <?php endforeach?>
					  <?php endif; ?>
					  </select>
                    </div>
					<button type="button" disabled="disabled" name="agregar" id="agregar" title="Presione aquí para GUARDAR el registro"  class="btn btn-primary"> <i class="fa fa-floppy-o"></i> Guardar</button>
                    <button type="button" disabled="disabled" name="cancelar" title="Presione aquí para CANCELAR el registro" id="cancelar" class="btn btn-danger"> <i class="fa fa-undo"></i> Cancelar</button>
                </form>    
            </div>
        </div>
    </div>    
</div>