<div class="row">                                                                               
<div class="col-lg-12">
    <form name="form_modulo_agregar" id="form_modulo_agregar" method="post" autocomplete="off" action="">    
	<div class="panel panel-default">
		<div class="panel-heading">Información de la Organizacion</div>
		<div class="panel-body">
			<input name="guardar" id="guardar" type="hidden" value="1" /> 
                            
                        <div class="form-group col-xs-6">
                            <label class="control-label">Empresa</label>
                            <select class="form-control" name="emp" id="emp" required  >
                            <option value="-">-TODOS-</option>
                            <?php if(isset($this->emp)&& count($this->emp)): ?>
                                    <?php foreach ($this->emp as $val): ?>
                                    <option value="<?php echo $val['id_empresa'] ?>"><?php echo strtoupper($val['nombre_empresa']) ?> </option>
                                    <?php endforeach; ?>
                            <?php endif; ?>
                            </select>  
                        </div>
			  <div class="form-group col-xs-6">
                                <label class="control-label">*Nombre:</label>
				<input name="nombre" type="text" maxlength="60" class="form-control alfa_nom"  id="nombre" placeholder="Ingrese nombre de la Organizacion" required />
			  </div>
			  <div class="form-group col-xs-6">
				<label>*Descripción:</label>
				<input name="descripcion" type="text" maxlength="100" class="form-control alfa_desc" id="descripcion" placeholder="Ingrese descripción de la Organizacion" required >            
			  </div>
			  <div class="form-group col-xs-3">
                            <label class="control-label">Tipo Organizacion</label>
                            <select class="form-control" name="tipo" id="tipo" required  >
                                <option value="-">-Seleccione-</option>                                
                                <option value="SUCURSAL">SUCURSAL</option>
                                <option value="FILIAL">FILIAL</option>
                                
                            </select>  
                         </div>
                        <div class="form-group col-xs-3">
                            <label class="control-label">Condición</label>
                            <select class="form-control" name="condicion" id="condicion" required  >
                                <option value="-">-Seleccione-</option>                                
                                <option value="SIN IMPLEMENTAR">Sin Implementar</option>
                                <option value="IMPLEMENTADO">Implementado</option>
                                <option value="OCULTO">Oculto</option>
                            </select>  
                        </div>
                      
		</div>
	</div>
            <div class="panel panel-default">
            <div class="panel-heading">Datos de Referencia</div>
            <div class="panel-body">
                <div class="form-group col-xs-6">
                    <label>Estado: ***</label>
                    <select class="form-control" name="estado" id="estado" required  />
                         <option value="-">-Seleccione-</option>
                         <?php if(isset($this->esta) && count($this->esta)):  ?>
                         <?php foreach($this->esta as $val): ?>
                             <option value="<?php echo $val['id_estado']  ?>"><?php echo $val['descripcion_estado'] ?></option>
                         <?php endforeach; ?>
                         <?php endif; ?>
                    </select>
                </div>
                <div class="form-group col-xs-6">
                    <label>Municipio: ***</label>
                    <select class="form-control"  name="municipio" id="municipio" required />
                         <option value="-">-Seleccione-</option>
                         <?php if(isset($this->muni) && count($this->muni)):  ?>
                         <?php foreach($this->muni as $val): ?>
                             <option value="<?php echo $val['id_municipio']  ?>"><?php echo $val['descripcion_municipio'] ?></option>
                         <?php endforeach; ?>
                         <?php endif; ?>
                    </select>
                </div>
                <div class="form-group col-xs-6">
                    <label>Parroquia: ***</label>
                    <select class="form-control"  name="parroquia" id="parroquia" required />
                     <option value="-">-Seleccione-</option>
                     <?php if(isset($this->parr) && count($this->parr)):  ?>
                     <?php foreach($this->parr as $val): ?>
                         <option value="<?php echo $val['id_parroquia']  ?>"><?php echo $val['descripcion_parroquia'] ?></option>
                     <?php endforeach; ?>
                     <?php endif; ?>
                    </select>
                </div>
                <div class="form-group col-xs-6">
                    <label>Sector: ***</label>
                    <select class="form-control"  name="sector" id="sector" required />
                     <option value="-">-Seleccione-</option>
                     <?php if(isset($this->sect) && count($this->sect)):  ?>
                     <?php foreach($this->sect as $val): ?>
                         <option value="<?php echo $val['id_sector']  ?>"><?php echo $val['descripcion_sector'] ?></option>
                     <?php endforeach; ?>
                     <?php endif; ?>
                    </select>
                </div>
                <div class="form-group col-xs-6">
                    <label>Dirección Fiscal:</label>
                    <input name="direccion" maxlength="100"  type="text" class="form-control" id="direccion" placeholder="*** Ingrese dirección de domicilio" required >  
                </div>
                <div class="form-group col-xs-6">
                    <label>Teléfono Local:</label>
                    <input name="local" id="local" maxlength="11"   type="text" class="form-control" placeholder="Ej.: 02552569856"  />
                </div>
                <div class="form-group col-xs-6">
                    <label>Correo Electrónico:</label>
                    <input type="email" maxlength="100"  class="form-control" name="correo" id="correo" placeholder="Ej.: micorreo@hotmail.com"  />
                </div>
            </div>
        </div>
    <br/>          
        <button type="submit" name="agregar" id="agregar" title="Presione aquí para Guardar el registro" class="btn btn-primary" ><i class="fa fa-floppy-o"></i> Guardar</button>
        <a href="<?php echo BASE_URL ?>desarrollo/modulo/index">
        <button type="button" title="Presione aquí para SALIR Y CANCELAR el registro" class="btn btn-danger"><i class="fa fa-undo"></i> Cancelar</button>
        </a>          
    <br/>
    </form> 
</div>
</div>