<div class="row">
	
    <div class="col-lg-12 col-md-6">
            
           <div class="panel panel-default">
           <div class="">
                <nav class="navbar navbar-default">
                    <div class="container-fluid">
                        <div class="navbar-header navbar-btn">
                            <a class="" href="<?php echo BASE_URL ?>configuracion/organizacion/agregar/" title="Agregar Nueva Organizacion"><button class="btn btn-default"><i class="fa fa-plus"></i></button></a>
                            <a class="" target="_blank" href="<?php echo BASE_URL ?>reporte/index/catOrganizacion/" title="Imprimir Listado de Compras"><button class="btn btn-default"><i class="fa fa-print"></i></button></a>				
			</div>  
                        <form class="navbar-form navbar-right" role="search" action="" method="post">
                            <div class="form-group">
                                <input type="text" name="busqueda" class="form-control alfa_desc" placeholder="Filtrar nombre y/o apellido">
                            </div>
                            <button type="submit" class="btn btn-default"><i  class="fa fa-search" > Buscar</i></button>
                        </form>    				
		    </div>
                </nav>
            </div>
            <div class="panel-body">
                <div class="table-responsive">
                    <table class="table table-hover">
                        <thead>
                            <tr class="bg-light-blue-active">
                                <th>Nro</th>
                                <th>Fecha</th>
                                <th>Nombre</th>
                                <th>Direccion</th>
				<th>Telefono</th>
                                <th>Tipo</th>                              
                                <th>Condicion</th>
                                <th width="30"></th>
                                <th width="30"></th>
				<th width="30"></th>
                            </tr>
                        </thead>
                        <tbody>
                        <?php if(isset($this->lista) && count($this->lista)) :?>
                            <?php foreach ($this->lista as $val) :?>
                            <tr>
                                <td><?php echo $val['id_organizacion'] ?></td>
				<td><?php echo date('d-m-Y',strtotime($val['fecha_creado'])) ?></td> 
				<td><?php echo strtoupper($val['nombre_organizacion']) ?></td>
                                <td><?php echo strtoupper($val['direccion_organizacion']) ?></td>
                                <td><?php echo strtoupper($val['telefono_organizacion']) ?></td>
                                <td><?php echo $val['tipo_organizacion'] ?></td>
                                <td><?php echo $val['condicion_organizacion'] ?></td>
                                <td>
                                    <?php if($val['estatus_organizacion']==1): ?>
                                      <button class="buscar btn btn-default"  data-toggle="modal" data-target=".bs-example-modal-lg"  data-id="<?php echo $val['id_organizacion'] ?>" ><i class="fa fa-search"></i></button>
                                    <?php endif; ?>
                                </td>
                                <td>  
                                    <?php if($val['estatus_organizacion']==1): ?>
                                        <button class="eliminar btn btn-default" value="<?php echo $val['id_organizacion'] ?>" ><i class="fa fa-trash-o"></i></button>      
                                    <?php endif; ?>  
                                </td>
                                <?php if($val['estatus_organizacion']==1): ?>
				<td><a href="<?php echo BASE_URL ?>compra/compras/distribuirGasto/<?php echo $val['id_organizacion'] ?>"><button class="btn btn-default" title="Distribucion de Gastos" value="" ><i class="fa fa-recycle"></i></button></a></td>
				<?php endif; ?>  
                            </tr>
                            <?php endforeach; ?>
                        <?php endif; ?>    
                        </tbody>
                    </table>
                                
                </div>
            </div>                
            <div class="panel-footer" >
                <p>
                    <?php if(isset($this->paginacion)) echo $this->paginacion; ?>
                </p>
            </div>
        </div>    
    </div>        
</div>
<div class="modal fade bs-example-modal-lg" id="compra_modal"  tabindex="-1" role="dialog" aria-labelledby="myLargeModalLabel">
  <div class="modal-dialog modal-lg">
    <div class="modal-content">
      <div class="modal-header bg-teal-active">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
		<h3>Recibo de Compra</h3>
      </div>
      <div class="modal-body">
          <div class="panel-default">
              <div class="panel-body">
                <div class="form-group col-md-3">
                    <label>Nro de Compra</label>
                    <input name="nro" id="nro" type="text" class="form-control " value="" />
                </div>
                <div class="form-group col-md-3">
                    <label>Fecha</label>
                    <input name="fecha" id="fecha" type="text" class="form-control" value="" />
                </div>
                <div class="form-group col-md-5">
                    <label>Proveedor</label>
                    <input name="proveedor" id="proveedor" type="text" class="form-control" value="" />
                </div>
              </div>    
          </div>
          <div class="panel-default">
              <div class="panel-body">
                    <div id="tabla-detalle">
                        <div class="table-responsive">
                          <table class="table table-bordered" id="tabla">
                              <thead>
                                  <tr class="bg-teal-active" >
                                      <th width='120'>Código</th>
                                      <th width='400'>Descripción</th>
                                      <th width='120'>Precio</th>
                                      <th width='100'>Cantidad</th>
                                      <th width='120'>Monto</th>
                                      <th width='90'>Iva %</th>
                                      <th width='120'>Total</th>                                    
                                  </tr>
                              </thead>
                              <tbody>
                              </tbody>
                          </table>
                      </div>
                    </div>
                    <div>
                            <div class="text-right">
                                    <h4 style="margin-bottom:0px;margin-top:10px;padding:0px;">Totales</h4>
                                    <hr style="margin:0px;margin-bottom:8px;">
                                    <div class="form-inline" >
                                            <div class="form-group">
                                                    <label style="margin-left:25px">Sub total</label>
                                                    <input type="text" name="subtotal" id="subtotal" class="form-control text-right" value="0" readonly="true" />
                                            </div>
                                            <div class="form-group">
                                                    <label style="margin-left:25px">Total Iva</label>
                                                    <input type="text" name="iva" id="iva" class="form-control text-right" value="0" readonly="true" />
                                            </div>
                                            <div class="form-group">
                                                    <label style="margin-left:25px">Total</label>
                                                    <input type="text" name="total" id="total" class="form-control text-right" value="0" readonly="true" />
                                            </div>
                                    </div>
                                    <hr />
                            </div>	
                            <div id="enlace"></div>
                      </div>
                  </div>
          </div>
      </div>    
    </div>
  </div>
</div>
