<div class="row">
	<form name="form-recep" method="post" autocomplete="off" action="">
		<input name="guardar" type="hidden" value="1" />
		<div class="col-lg-12">
			<div class="col-md-8 col-md-offset-2">
				<div class="panel panel-default">
					<nav class="navbar navbar-default">
						<div class="container-fluid">			
								  							
						</div>
					</nav>
					<div class="panel-body">
						<article>
							<p>Para la Eliminacion de una Factura debe llenar el siguiente formulario </p>
							
						</article>
						<hr>
						<div class="form-group">
							<label>Motivo de la anulacion</label>
							<textarea name="motivo" id="motivo" class="form-control">
								
							</textarea>
						</div>
						<div class="form-group">
							<label>Codigo de Autorizacion</label>
							<input name="codigo" type="text" class="form-control" id="codigo"   required   />
						</div>	
					</div>
					 
				</div>
				<button type="button" class="btn btn-danger" id="cancelar"><i class="fa fa-undo"></i> Cancelar</button>
	            <button type="button" class="btn btn-primary" id="guardar" oninvalid="alert('Llene todos los campos obligatorios ....');"><i class="fa fa-floppy-o"></i> Continuar</button>
	            <br/>
	            <br/>  
			</div>
		</div>
	</form>
</div>