<div class="row">
    <div class="col-lg-12 col-md-6">
        <div class="panel panel-default">
           <div class="">
                <nav class="navbar navbar-default">
                    <div class="container-fluid">
                        <div class="navbar-header">
                            <a class="navbar-brand" href="<?php echo BASE_URL ?>compra/proveedor/agregar/" title="Agregar Nuevo proveedor"><button><i class="fa fa-plus"></i></button></a>
                            <a class="navbar-brand" target="_blank" href="<?php echo BASE_URL ?>reporte/index/catProveedor/" title="Imprimir Catálogo"><button><i class="fa fa-print"></i></button></a>
                        </div>  
                        <form class="navbar-form navbar-right" role="search" action="" method="post">
                            <div class="form-group">
                                <input type="text" name="busqueda" class="form-control alfa_desc" placeholder="Filtrar nombre y/o apellido">
                            </div>
                            <button type="submit" class="btn btn-default"><i  class="fa fa-search" > Buscar</i></button>
                        </form>    
                    </div>
                </nav>
            </div>
            <div class="panel-body">
                <div class="table-responsive">
                    <table class="table table-bordered">
                        <thead>
                            <tr class="bg-teal-active">
                                <th>Rif</th>
                                <th>Razón Social</th>
                                <th>Dirección Fiscal</th>
                                <th>Teléfono</th>
                                <th>Contacto</th>
                                <th width="30"></th>
                                <th width="30"></th>
                            </tr>
                        </thead>
                        <tbody>
                        <?php if(isset($this->proveedor) && count($this->proveedor)) :?>
                            <?php foreach ($this->proveedor as $val) :?>
                            <tr>
                                <td><?php echo $val['rif_proveedor'] ?></td>
                                <td><?php echo ucwords($val['razon_social_proveedor']) ?></td>
                                <td><?php echo ucwords($val['direccion_fiscal_proveedor']) ?></td>
                                <td><?php echo $val['telefono_proveedor'] ?></td>
                                <td><?php echo ucwords($val['nombre_contacto_proveedor']) ?></td>
                                <td>
                                    <?php if($val['estatus_proveedor']==1): ?>
                                    <a href="<?php echo BASE_URL ?>archivo/proveedor/editar/<?php echo $val['id_proveedor'] ?>"  >
                                    <button class="editar" title="Presione aquí para EDITAR" value="<?php echo $val['id_proveedor'] ?>" ><i  class="fa fa-pencil-square-o"></i></button>
                                    <?php endif; ?>
                                </td>
                                <td>  
                                    <?php if($val['estatus_proveedor']==1): ?>
                                        <button class="eliminar" title="Presione aquí para ELIMINAR" value="<?php echo $val['id_proveedor'] ?>" ><i class="fa fa-trash-o"></i></button>
                                    <?php elseif($val['estatus_proveedor']==9):  ?>
                                        <button class="restaurar" title="Presione aquí para RESTAURAR" value="<?php echo $val['id_proveedor'] ?>" ><i class="fa fa-recycle"></i></button>
                                    <?php endif; ?>  
                                </td>
                            </tr>
                            <?php endforeach; ?>
                        <?php endif; ?>    
                        </tbody>
                    </table>
                                
                </div>
            </div>                
            <div class="panel-footer" >
                <p>
                    <?php if(isset($this->paginacion)) echo $this->paginacion; ?>
                </p>
            </div>
        </div>    
    </div>        
</div>