<div class="row">
    <div class="col-lg-12 col-md-6">
        <div class="panel panel-default">
            <div class="">
                <nav class="navbar navbar-default">
                    <div class="container-fluid">
                        <div class="navbar-header">
                            <a href="<?php echo BASE_URL ?>venta/factura/agregar/" title="Agregar Factura"><button class="btn btn-default navbar-btn"><i class="fa fa-plus"></i></button></a>
                        </div>  
                        <form class="navbar-form navbar-right" role="search" action="" method="post">
                            <div class="form-group">
                                <input type="text" name="busqueda" class="form-control" placeholder="Filtrar descripción">
                            </div>
                            <button type="submit" class="btn btn-default"><i  class="fa fa-search" > Buscar</i></button>
                        </form>    
                    </div>
                </nav>
            </div>
          <div class="panel-body">
            <div class="table-responsive">
                <table class="table table-bordered">
                    <thead>
                    <tr class="bg-teal-active">
			<th>Nro.</th>
                        <th>Fecha</th>
                        <th>Rif</th>
                        <th>Razon Social</th>
                        <th>Direccion Fiscal</th>
                        <th>Subtotal</th>
                        <th>I.V.A</th>
                        <th>Total</th>
                        <th>Estatus</th>
                        <th width="30"></th>
			<th width="30"></th>
                        <th width="30"></th>
                    </tr>
                    </thead>
                    <tbody>
                    <?php if(isset($this->lista) && count($this->lista)) :?>
                        <?php foreach ($this->lista as $val) :?>
                        <tr>
                            <td><?php echo $val['id_venta'] ?></td>
                            
                            
                            <td><button class="buscar btn btn-default"  data-toggle="modal" data-target=".bs-example-modal-lg"  data-id="<?php echo $val['id_venta'] ?>" ><i class="fa fa-search"></i></button></td>
                            <td><a href="<?php echo BASE_URL ?>venta/factura/anular/<?php echo $val['id_venta'] ?>"><button  class="btn btn-default"><i class="fa fa-trash-o"></i></button></a></td>
                            <td><a href="<?php echo BASE_URL ?>reporte/index/impFV/<?php echo $val['id_venta'] ?>" target="_blank"><button  class="btn btn-default"><i class="fa fa-print"></i></button></a></td>
                        </tr>
                        <?php endforeach; ?>
                    <?php endif; ?>    
                    </tbody>
                </table>
                
                <p>
                        <?php if(isset($this->paginacion)) echo $this->paginacion; ?>
                </p>
            </div>
          </div>

        </div>
    </div>
        
</div>