<div class="row">
        <div class="col-lg-8 col-md-6">
        <div class="panel panel-default">
        <div class="">
        <nav class="navbar navbar-default">
            <div class="container-fluid">
                <div class="navbar-header">
                    
                </div>  
                <form class="navbar-form navbar-right" role="search" action="" method="post">
                    <div class="form-group">
                        <input type="text" name="busqueda" class="form-control" placeholder="Filtrar descripción de cargo">
                    </div>
                    <button type="submit" class="btn btn-default"><i  class="fa fa-search" > Buscar</i></button>
                </form>    
            </div>
        </nav>
            </div>
        
          <div class="panel-body">
            <div class="table-responsive">
                <table class="table table-hover">
                    <thead>
                    <tr>
                        <th>Código</th>
                        <th>Descripción</th>
                        <th>Departamento</th>
                        <th>Creación</td>
                        <th>Estatus</th>
                        <th></th>
                        <th></th>
                    </tr>
                    </thead>
                    <tbody>
                    <?php $i = 1; ?>    
                    <?php if(isset($this->lista) && count($this->lista)) :?>
                        <?php foreach ($this->lista as $val) :?>
                        
                        <tr>
                            <td><?php echo $val['id_cargo'] ?></td>
                            <td><?php echo ucfirst($val['nombre_cargo']) ?></td>
                            <td><?php echo ucfirst($val['medida']) ?></td>
                            <td><?php echo date('d-m-Y',strtotime($val['fecha_creacion'])) ?></td>
                            <td><?php echo ($val['estatus_cargo']==1)?'Activo':'Inactivo' ?></td>
                            <td>
                                <?php if($val['estatus_cargo']==1): ?>
                                <button class="boton" title="Presione aquí para EDITAR" value="<?php echo $val['id_cargo'] ?>" ><i  class="fa fa-pencil-square-o"></i></button>
                                <?php endif; ?>
                            </td>
                            <td>
                                <?php if($val['estatus_cargo']==1): ?>
                                <button class="eliminar" title="Presione aquí para ELIMINAR" value="<?php echo $val['id_cargo'] ?>"><i class="fa fa-trash-o"></i></button>
                                <?php endif; ?>
                            </td>
                        </tr>
                        <?php $i++; ?>
                        <?php endforeach; ?>
                    <?php endif; ?>    
                    </tbody>
                </table>
                <hr>
                <p>
                      <?php if(isset($this->paginacion)) echo $this->paginacion;  ?>
                </p>
            </div>
          </div>

        </div>
    </div>
    <div class="col-lg-4 col-md-6">
        <div class="panel panel-default">
            <div class="panel-heading">Gestión de Cargo Laboral</div>
            <div class="panel-body">
                <form name="cargo" method="post" autocomplete="off" action="<?php echo BASE_URL ?>configuracion/cargo/agregar/">
                    <input name="guardar" type="hidden" value="1" id="guardar">
                    <input name="id" type="hidden" value="0" id="id">
                    <div class="form-group">
                      <label>Descripción:</label>
                      <input name="descripcion" type="text" class="form-control" id="descripcion" placeholder="Ingrese la descripción del cargo laboral" required="" />
                    </div>
                    <div class="form-group">
                      <label>Departamento:</label>
                      <select name="medida" id="medida" class="form-control">
                          <option>-Seleccione-</option>
                          <?php if(isset($this->medida) && count($this->medida)): ?>
                                <?php foreach ($this->medida as $val): ?>
                                    <?php if($val['estatus_departamento']==1): ?>
                                    <option value="<?php echo $val['id_departamento']  ?>"><?php echo $val['descripcion_departamento']  ?></option>   
                                    <?php endif; ?>    
                                <?php endforeach; ?>
                          <?php endif; ?>
                      </select>
                    </div>
                    <button type="submit" class="btn btn-primary"  >Guardar</button>
                    <button type="reset" class="btn btn-danger">Limpiar</button>
                </form>    
            </div>
        </div>
    </div>    
</div>
