<div class="row">
        <div class="col-lg-8 col-md-6">
        <div class="panel panel-default">
            <div class="">
                <nav class="navbar navbar-default">
                    <div class="container-fluid">
                        <div class="navbar-header">
                           
                        </div>  
                        <form class="navbar-form navbar-right" role="search" action="" method="post">
                            <div class="form-group">
                                <input type="text" name="busqueda" class="form-control" placeholder="Filtrar nombre">
                            </div>
                            <button type="submit" class="btn btn-default"><i  class="fa fa-search" > Buscar</i></button>
                        </form>    
                    </div>
                </nav>
            </div>
          <div class="panel-body">
            <div class="table-responsive">
                <table class="table table-hover">
                    <thead>
                    <tr>
                        <th>Código</th>
                        <th>Nombre</th>
                        <th>Estatus</td>
                        <th></th>
                        <th></th>
                    </tr>
                    </thead>
                    <tbody>
                    <?php $i = 1; ?>    
                    <?php if(isset($this->lista) && count($this->lista)) :?>
                        <?php foreach ($this->lista as $val) :?>
                        
                        <tr>
                            <td><?php echo $val['id_marca'] ?></td>
                            <td><?php echo ucfirst($val['nombre_marca']) ?></td>
                            <td><?php echo ($val['estatus_marca']==1)?'Activo' : 'Inactivo' ?></td>
                            <td>
                                <?php if($val['estatus_marca']==1): ?>
                                <button class="editar" title="Presione aquí para EDITAR" value="<?php echo $val['id_marca'] ?>" ><i  class="fa fa-pencil-square-o"></i></button>
                                <?php endif; ?>
                            </td>
                            <td>
                                <?php if($val['estatus_marca']==1): ?>
                                <button class="eliminar" title="Presione aquí para ELIMINAR" value="<?php echo $val['id_marca'] ?>"><i class="fa fa-trash-o"></i></button>
                                <?php endif; ?>
                            </td>
                        </tr>
                        <?php $i++; ?>
                        <?php endforeach; ?>
                    <?php endif; ?>    
                    </tbody>
                </table>
                <hr>
                <p>
                      <?php if(isset($this->paginacion)) echo $this->paginacion; ?>
                </p>
            </div>
          </div>

        </div>
    </div>
    <div class="col-lg-4 col-md-6">
        <div class="panel panel-default">
            <div class="panel-heading">Gestión para Marca de Transporte</div>
            <div class="panel-body">
                <form name="marcaTransporte" id="marcaTransporte" method="post" autocomplete="off" action="<?php echo BASE_URL ?>archivo/marcaTransporte/agregar/">
                    <input name="guardar" type="hidden" value="1" id="guardar">
                    <input name="id" type="hidden" value="0" id="id">
                    <input name="aux" type="hidden" value="0" id="aux">
                    <div class="form-group">
                      <label>***Nombre:</label>
                      <input name="descripcion" type="text" maxlength="100" class="form-control" id="descripcion" placeholder="Ingrese nombre de la marca de transporte" required />
                    </div>
                    <button type="button" name="agregar" id="agregar" title="Presione aquí para GUARDAR el registro" class="btn btn-primary" >Guardar</button>
                    <button type="button" name="limpiar" id="limpiar" title="Presione aquí para VACIAR el formulario" class="btn btn-danger">Limpiar</button>
                </form>    
            </div>
        </div>
    </div>    
</div>