<div class="row">
        <div class="col-lg-12 col-md-6">
            <ul class="nav nav-tabs">
				<li role="presentation" ><a href="<?php echo  BASE_URL ?>compra/planificacion/index/"><i class="fa fa-calendar"></i> Planificación de Compra </a></li>
				<li role="presentation" class="active"><a href="#"><i class="fa fa-crosshairs"></i> Evaluación y Seguimiento</a></li>				
				<li role="presentation" ><a href="<?php echo  BASE_URL ?>compra/planificacion/concepto/"><i class="fa fa-tags"></i> Conceptos de Planificación</a></li>				
			</ul>
			<div class="panel panel-default">
				  
					
				<div class="panel-body">
					<div class="box">
						<div class="box-header with-border">
							<h3 class="box-title">Comparativo  Planificado / Ejecutado</h3>												
						</div>
						<div class="box-body">
							<div class="row">
								<div class="col-lg-8">
									<div class="chert">
										<canvas id="speedChart" style="width:100%;"></canvas>
									</div>
								</div>
								<div class="col-lg-4">
									
									  <p class="text-center">
										<strong>Goal Completion</strong>
									  </p>

									  <div class="progress-group">
										<span class="progress-text">Add Products to Cart</span>
										<span class="progress-number"><b>160</b>/200</span>

										<div class="progress sm">
										  <div class="progress-bar progress-bar-aqua" style="width: 80%"></div>
										</div>
									  </div>
									  <!-- /.progress-group -->
									  <div class="progress-group">
										<span class="progress-text">Complete Purchase</span>
										<span class="progress-number"><b>310</b>/400</span>

										<div class="progress sm">
										  <div class="progress-bar progress-bar-red" style="width: 80%"></div>
										</div>
									  </div>
									  <!-- /.progress-group -->
									  <div class="progress-group">
										<span class="progress-text">Visit Premium Page</span>
										<span class="progress-number"><b>480</b>/800</span>

										<div class="progress sm">
										  <div class="progress-bar progress-bar-green" style="width: 80%"></div>
										</div>
									  </div>
									  <!-- /.progress-group -->
									  <div class="progress-group">
										<span class="progress-text">Send Inquiries</span>
										<span class="progress-number"><b>250</b>/500</span>

										<div class="progress sm">
										  <div class="progress-bar progress-bar-yellow" style="width: 80%"></div>
										</div>
									  </div>
									  <!-- /.progress-group -->
								</div>
							</div>
							</div>
						</div>
					
					
					
					<div class="box box-info">
						<div class="box-header with-border">
							<h3 class="box-title">Detalle de Planificacion</h3>												
						</div>
						<div class="box-body">
						<?php if(isset($this->lista) && count($this->lista)>0): ?>
							<?php $i=0; ?>
							<?php foreach($this->lista as $row): ?>
							
							<div class=' panel-default'>
								<div class="panel-heading form-inline ">
									<div class="form-group ">
									<?php if($row['condicion'] == 'POR EVALUAR'):  ?>
										<input name="id" id="id<?php echo $i ?>" type="radio" value="<?php echo $row['id']  ?>" class="checkbox detalle" data-id="<?php echo $i  ?>" />	|						
									<?php endif; ?>
									</div>
									<div class="form-group ">
										<label>Fecha:</label>
										<?php echo $row['creacion'].'  |  '  ?>
									</div>
									<div class="form-group ">
										<label>Solicitante:</label>
										<?php echo $row['unidad'].'  |  ' ?>
									</div>
									<div class="form-group ">
										<label>Departamento:</label>
										<?php echo $row['dpto'].'  |  ' ?>
									</div>
									<div class="form-group ">
										<label>Objetivo:</label>
										<?php echo $row['concepto'].'  |  ' ?>
									</div>
									
								</div>
								<div id="det<?php echo $i ?>" class="tabla_detalle" >
									
								
								</div>
							</div>	
							<?php $i++; ?>
							<?php endforeach; ?>
						<?php endif; ?>
						</div|>
					</div>		
				</div>
				<div class="panel-footer" >
					<p>
						<?php if(isset($this->paginacion)) echo $this->paginacion; ?>
					</p>
				</div>
				</div>        
			</div>
		</div>	
</div>  

