<div class="row">
	
    <div class="col-lg-12 col-md-6">
        <div class="col-lg-12 col-md-6">
            <ul class="nav nav-tabs">
				<li role="presentation" class="active"><a href="#"><i class="fa fa-calendar"></i> Planificación de Compra </a></li>
				<li role="presentation" ><a href="<?php echo  BASE_URL ?>compra/planificacion/control/"><i class="fa fa-crosshairs"></i> Evaluación y Seguimiento</a></li>				
				<li role="presentation" ><a href="<?php echo  BASE_URL ?>compra/planificacion/concepto/"><i class="fa fa-tags"></i> Conceptos de Planificación</a></li>				
			</ul>
		<div class="panel panel-default">
           <div class="">
                <nav class="navbar navbar-default">
                    <div class="container-fluid">
                        <div class="navbar-header navbar-btn">
                            <a class="" href="<?php echo BASE_URL ?>compra/planificacion/agregar/" ><button class="btn btn-default"><i class="fa fa-plus"></i></button></a>
                            <a class="" target="_blank" href="<?php echo BASE_URL ?>reporte/index/catCompra/" ><button class="btn btn-default"><i class="fa fa-print"></i></button></a>
							
						</div>  
                        <form class="navbar-form navbar-right" role="search" action="" method="post">
                            <div class="form-group">
                                <input type="text" name="busqueda" class="form-control alfa_desc" placeholder="Filtrar nombre y/o apellido">
                            </div>
                            <button type="submit" class="btn btn-default"><i  class="fa fa-search" > Buscar</i></button>
                        </form>    
						
					</div>
                </nav>
            </div>
            <div class="panel-body">
                <div class="table-responsive">
                    <table class="table  table-hover">
                        <thead>
                            <tr class="bg-light-blue-active">
                                <th>Nro</th>
				<th>Unidad Operativa</th>
                                <th>Departamento</th>
                                <th>Inicio</th>
				<th>Finalizacion</th>                              
                                <th>Objetivo</th>
								
                                <th width="30"></th>
                                <th width="30"></th>
								
                            </tr>
                        </thead>
                        <tbody>
                        <?php if(isset($this->lista) && count($this->lista)) :?>
                            <?php foreach ($this->lista as $val) :?>
                            <tr>
                                <td><?php echo $val['id_planificacion'] ?></td>
				<td><?php echo $val['unidad'] ?></td>
				<td><?php echo strtoupper($val['departamento']) ?></td>
				<td><?php echo date('d-m-Y',strtotime($val['fecha_inicio'])) ?></td>
                                <td><?php echo date('d-m-Y',strtotime($val['fecha_fin'])) ?></td>								
				<td><?php echo strtoupper($val['concepto']) ?></td>
                                
                                
                                <td>
                                    <?php if($val['estatus_pln']==1): ?>
                                      <button class="buscar btn btn-default"  data-toggle="modal" data-target=".bs-example-modal-lg"  data-id="<?php echo $val['id_planificacion'] ?>" ><i class="fa fa-search"></i></button>
                                    <?php endif; ?>
                                </td>
                                <td>  
                                    <?php if($val['estatus_pln']==1): ?>
                                        <button class="eliminar btn btn-default" value="<?php echo $val['id_planificacion'] ?>" ><i class="fa fa-trash-o"></i></button>      
                                    <?php endif; ?>  
                                </td>
                                
                            </tr>
                            <?php endforeach; ?>
                        <?php endif; ?>    
                        </tbody>
                    </table>
                                
                </div>
            </div>                
            <div class="panel-footer" >
                <p>
                    <?php if(isset($this->paginacion)) echo $this->paginacion; ?>
                </p>
            </div>
        </div>    
    </div>        
</div>
<div class="modal fade bs-example-modal-lg" id="compra_modal"  tabindex="-1" role="dialog" aria-labelledby="myLargeModalLabel">
  <div class="modal-dialog modal-lg">
    <div class="modal-content">
      <div class="modal-header bg-teal-active">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
		<h3>Planificacion de Compra</h3>
      </div>
      <div class="modal-body">
          <div class="panel-default">
               <div class="panel-default">
              <div class="panel-body">
                <div class="form-group col-md-4">
                    <label>Nro de Planificacion</label>
                    <input name="nro" id="nro" type="text" class="form-control " value="" />
                </div>
                <div class="form-group col-md-4">
                    <label>Unidad Operativa</label>
                    <input name="unidad" id="unidad" type="text" class="form-control" value="" />
                </div>
				<div class="form-group col-md-4">
                    <label>Departamento</label>
                    <input name="departamento" id="departamento" type="text" class="form-control" value="" />
                </div>
				<div class="form-group col-md-3">
                    <label>Inicio</label>
                    <input name="inicio" id="inicio" type="text" class="form-control" value="" />
                </div>
				<div class="form-group col-md-3">
                    <label>Finalizacion</label>
                    <input name="final" id="final" type="text" class="form-control" value="" />
                </div>
                
				<div class="form-group col-md-6">
                    <label>Objetivo de Planificacion</label>
                    <input name="objetivo" id="objetivo" type="text" class="form-control" value="" />
                </div>
              </div>    
          </div>  
          </div>
          <div class="panel-default">
              <div class="panel-body">
                    <div id="tabla-detalle">
                        <div class="table-responsive">
                          <table class="table table-bordered" id="tabla_pln">
                              <thead>
                                  <tr class="bg-teal-active" >
                                      <th width='120'>Nro Requisito</th>
                                      <th width='90'>Tipo</th>
									  <th width='400'>Descripción</th>
                                      <th width='120'>Cantidad</th>
                                      <th width='100'>Prioridad</th>
									  <th width='120'>Plazo</th>
									  									  
                                  </tr>
                              </thead>
                              <tbody>
							  
                              </tbody>
                          </table>
                      </div>
                    </div>
					
                  </div>
          </div>
      </div>    
    </div>
  </div>
</div>
