<div class="row">
<div class="col-lg-12">
<div class="panel panel-default"> 
	<form name="form_compra" method="post" autocomplete="off" action="<?php echo BASE_URL ?>compra/requisicion/agregar" id="form_compra">
	<nav class="navbar navbar-default">
		<div class="container-fluid">				
			<div class="navbar-header">
				<h4>Compras  /    Fecha: <?php echo date('d-m-Y') ?></h4>
			</div>	
			<div class="navbar-form navbar-right" >
				<label >Unidad Operativa</label>
				<select class="form-control input-sm" name="unidad" id="unidad" required  />
					<option value="-">-TODOS-</option>
					<?php if(isset($this->unidad)&& count($this->unidad)): ?>
						<?php foreach ($this->unidad as $val): ?>
						<option value="<?php echo $val['id_unidad_operativa'] ?>"><?php echo strtoupper($val['nombre_unidad_operativa']) ?> </option>
						<?php endforeach; ?>
					<?php endif; ?>
				</select>
				
				<label >Deposito</label>
				<select class="form-control input-sm" name="almacen" id="almacen" required  />
					<option value="">-Seleccione-</option>					
				</select>
			</div>					  							
		</div>
	</nav>
    <div class="panel-body">
    
    <input name="guardar" type="hidden" value="1" /> 
	<div class="col-lg-4">
            <div class="panel panel-default">                
                <div class="panel-heading "><h4 style="margin-bottom:0px;margin-top:2px;padding:2px;" >Inf. Adicional</h4></div>
                    <div class="panel-body">
					<div class="col-lg-12">
	                    <div class="form-group">    
	                        <label>Prioridad</label>
	                        <select name="prioridad" id="prioridad" class="form-control input-sm" disabled="true" >
	                            <option value="">-Seleccione-</option>
	                            <option value="BAJA">BAJA</option>
	                            <option value="MEDIA">MEDIA</option>
                                <option value="ALTA">ALTA</option>
	                        </select>    
	                    </div>
                    </div>
					<div class="col-lg-12">
	                    <div class="form-group col-lg-6">    
	                        <label>Fecha Requerida</label>
	                        <input name="fecha_requerida" id="fecha_requerida" type="date" class="form-control input-sm text-right" disabled="true" />    
	                    </div>
						<div class="form-group col-lg-6">    
	                        <label>Plazo(dias)</label>
	                        <input name="plazo" id="plazo" class="form-control input-sm text-right" disabled="true" />    
	                    </div>						
					</div>                                        
            </div>
            </div>       
    </div>
		
        <div class="col-lg-8">
            <div class="panel panel-info ">
                <div class="panel-heading bg-light-blue-gradient"><h4 style="margin-bottom:0px;margin-top:2px;padding:2px;">Comentarios</h4></div>
                <hr style="margin:0px;margin-bottom:4px;">
                <div class="panel-body">
                    <div class="col-lg-6">
	                <div class="form-group">    
	                   <label>Motivo de Requisicion</label>
	                   <textarea name="motivo" id="motivo" class="form-control " rows="3" disabled="true" ></textarea>    
	                </div>
                    </div>
                    <div class="col-lg-6">
	                <div class="form-group">    
	                    <label>Comentario de Requisicion</label>
	                    <textarea name="comentario" id="comentario" rows="3" class="form-control " disabled="true" ></textarea>    
                        </div>
                    </div>	
                </div>
            </div>

        </div>
        
        <div class="col-lg-12">    
            
            <div class="panel panel-default">
                
                <div class="panel-body">
                    <p>
                            <button class="btn btn-default input-sm"  id="agregar" type="button" disabled="true" ><i class="fa fa-plus"></i></button>
                    </p>
                    <div class="table-responsive">
                        <table class="table table-bordered" id="tabla">
                            <thead>
                                <tr class="bg-light-blue-active">
                                    
								<th width='120'>Codigo</th>
								<th width='130'>Tipo</th>
								<th width='450'>Descripcion</th>
								<th width='300'>Marca</th>
								<th width='100'>U/M</th>
								<th width='100'>Cantidad</th>
								<th></th>
								</tr>
                            </thead>
                            <tbody>
                                
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
	    <button type="button" class="btn btn-warning" id="cancelar"><i class="fa fa-eraser"></i> </button>
            <a href="<?php echo BASE_URL ?>compra/requisicion/index"><button type="button" class="btn btn-danger" id="cancelar"><i class="fa fa-undo"></i> </button></a>
            <button type="button" class="btn btn-primary" id="guardar" disabled="true" ><i class="fa fa-floppy-o"></i> </button>
            <br/>
            <br/>   
        </div>
      
         
	</div>
	</form>   
</div>
</div>    
</div>

<div class="modal fade" id="myModal" data-toggle="modal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
  <div class="modal-dialog modal-lg" role="document">
    <div class="modal-content">
      <div class="modal-header bg-info">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>  
        <label>Busqueda de Requisito</label>
      </div>
      <div class="modal-body">
      
        <div class="panel" >
        <div class="panel-body">
            <div class="form-group col-lg-4">
                <select name="tipo" id="tipo" class="form-control " >
                    <option value="">-Seleccione-</option>
                    <option value="SERVICIO">Servicio</option>
                    <option value="PRODUCTO">Producoto / Material</option>
                </select>
            
            </div>
            <div class="form-group col-lg-8">
                <input name="producto" id="producto" type="text" class="form-control"  />        
            </div>
        </div>      
        </div> 
          <input name="id_fila" id="id_fila" type="hidden" class="form-control"  />
          <div class="panel panel-default" >
              <div class="panel-body">
                  <div id="table_concepto">
                     <table class="table  table-bordered" id="tabla_prod"  >
			<thead>
                            <tr>           
                               <td class="cabecera" width="70">Codigo.</td>
                               <td class="cabecera" width="400">Nombre</td>
                               <td class="cabecera" width="250">Marca</td>
                               <td class="cabecera" width="100">U/M</td>
                               <td class="cabecera" width="30"></td>
                            </tr>
			</thead>
			<tbody>
			</tbody>
                     </table>
                  </div>   
              </div>
          </div>
      </div>
      <div class="modal-footer">
        
      </div>
    </div>
  </div>
</div>

