<div class="row">
        <div class="col-lg-12 col-md-6">
            <ul class="nav nav-tabs">
            <li role="presentation" class="active"><a href="#"> <i class="fa fa-calendar"></i> Listado Requisiciones </a></li>
            <li role="presentation"><a href="<?php echo  BASE_URL ?>compra/requisicion/control/"> <i class="fa fa-crosshairs"></i> Evaluacion y Seguimiento de Requisiciones</a></li>
        </ul>
        <div class="panel panel-default">
            <div class="">
                <nav class="navbar navbar-default">
                    <div class="container-fluid">
                        <div class="navbar-header navbar-btn">
                            <a class="" href="<?php echo BASE_URL ?>compra/requisicion/agregar/" ><button class="btn btn-default" type="button"><i class="fa fa-plus"></i></button></a>
                            <a class="" href="<?php echo BASE_URL ?>reporte/index/print_ListaRecepcionProv/"  target="_blank"><button class="btn btn-default" type="button"><i class="fa fa-print"></i></button></a>
                        </div>
                        <form class="navbar-form navbar-right" role="search" action="" method="post">
                            <div class="form-group">
                                <label>Depósito</label>
                                <?php if(isset($this->depTrb) && count($this->depTrb)>0): ?>
                                <select name="deposito" id="deposito" class="form-control">
                                    <option value="0">TODOS</option>
                                <?php foreach($this->depTrb as $dep): ?>
                                    <?php if(isset($this->depAct)&& $this->depAct==$dep['id_deposito']): ?>
                                    <option value="<?php echo $dep['id_deposito'] ?>" selected="true"><?php echo $dep['nombre_deposito'] ?></option>
                                    <?php else: ?>
                                    <option value="<?php echo $dep['id_deposito'] ?>"><?php echo $dep['nombre_deposito'] ?></option>
                                    <?php endif; ?>
                                <?php endforeach; ?>
                                </select>
                                <?php endif; ?>
                                <input type="text" name="busqueda" class="form-control" placeholder="Busqueda">
                            </div>
                            <button type="submit" class="btn btn-default">Enviar</button>
                        </form>
                    </div>
                </nav>
            </div>

        <div class="panel-body">
        <div class="table-responsive">
            <table class="table table-bordered">
                <thead>
                <tr class="bg-light-blue-active">
                  <th width="70">Código</th>
                  <th width="80">Fecha</th>
                  <th width="180">Unidad Operativa</th>
                  <th width="180">Almacen</th>
                  <th width="150">Tipo Requisicion</th>
				  <th width="150">Prioridad</th>
                  <th width="150">Condicion</th>
                  <th width="24"></th>
                  <th width="24"></th>
                  <th width="24"></th>
                </tr>
                </thead>
                <tbody>
                <?php if(isset($this->lista) && count($this->lista)) :?>
                    <?php foreach ($this->lista as $val) :?>
                    <tr>
                        <td><?php echo $val['id_requisicion'] ?></td>
                        <td><?php echo date('d-m-Y',strtotime($val['fecha_requisicion'])); ?></td>
                        <td><?php echo strtoupper(($val['nombre_unidad_operativa'])) ?></td>
                        <td><?php echo strtoupper($val['nombre_deposito']) ?></td>
                        <td><?php echo strtoupper($val['tipo_requisicion']) ?></td>
						<td><?php echo strtoupper($val['prioridad_requisicion']) ?></td>
                        <td><?php echo $val['condicion_requisicion'] ?></td>
                        <td><button type="button" class="editar btn btn-default" data-toggle="modal" data-target=".bs-example-modal-lg"  data-id="<?php echo $val['id_requisicion'] ?>"  ><i class="fa fa-search"></i></button></td>
                        <td>
                            <button data-id="<?php echo $val['id_requisicion'] ?>" class="eliminarSol btn btn-default"> <i class="fa fa-trash-o"></i></button>
                        </td>
                        <td>
                            <a href="<?php echo BASE_URL ?>reporte/index/print_Recepcion/<?php echo $val['id_requisicion'] ?>" target="_blank" >
                                <button class="btn btn-default"> <i class="fa fa-print"></i></button></a>
                        </td>
                    </tr>
                    <?php endforeach; ?>
                <?php endif; ?>
                </tbody>
            </table>


        </div>
      </div>
	  <div class="panel-footer" >
			<p>
				<?php if(isset($this->paginacion)) echo $this->paginacion; ?>
			</p>
	   </div>
    </div>
</div>
</div>

<div class="modal fade bs-example-modal-lg" tabindex="-1" role="dialog" aria-labelledby="myLargeModalLabel">
  <div class="modal-dialog modal-lg">
    <div class="modal-content">
      <div class="modal-header colorHeaderTable">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
		<h3>Requisicion de Compra</h3>
      </div>
      <div class="modal-body">
          <div class="panel-default">
              <div class="panel-body">
                <div class="form-group col-md-2">
                    <label>Nro de Requisicion</label>
                    <input name="nro" id="nro" type="text" class="form-control text-right input-sm" value="" />
                </div>
                <div class="form-group col-md-2">
                    <label>Fecha</label>
                    <input name="fecha" id="fecha" type="text" class="form-control input-sm" value="" />
                </div>
                <div class="form-group col-md-4">
                    <label>Unidad Operativa</label>
                    <input name="unidad" id="unidad" type="text" class="form-control input-sm" value="" />
                </div>
		<div class="form-group col-md-4">
                    <label>Almacen Solicitante</label>
                    <input name="depo" id="depo" type="text" class="form-control input-sm" value="" />
                </div>
		<div class="form-group col-md-2">
                <label>Plazo (Dias)</label>
                    <input name="plazo" id="plazo" type="text" class="form-control text-right input-sm" value="" />
                </div>
		<div class="form-group col-md-2">
                    <label>Prioridad </label>
                    <input name="prioridad" id="prioridad" type="text" class="form-control input-sm" value="" />
                </div>
		<div class="form-group col-md-4">
                    <label>Motivo de Requisicion</label>
                    <input name="motivo" id="motivo" type="text" class="form-control input-sm" value="" />
                </div>
		<div class="form-group col-md-4">
                    <label>Comentario </label>
                    <input name="comentario" id="comentario" type="text" class="form-control input-sm" value="" />
                </div>
              </div>
          </div>
          <div class="panel-default">
              <div class="panel-body">
                    <div id="tabla-detalle">
                        <div class="table-responsive">
                          <table class="table table-bordered" id="tabla">
                              <thead>
                                  <tr class="bg-light-blue-active" >
                                      <th width='80'>Id</th>
                                      <th width='100'>Tipo</th>
                                      <th width='80'>Codigo</th>
                                      <th width='350'>Descripcion</th>
                                      <th width='100'>Cantidad</th>
                                      <th width='120'>Condicion</th>
                                      <th></th>
                                  </tr>
                              </thead>
                              <tbody>

                              </tbody>
                          </table>
                      </div>
                    </div>
                  <div>
                      <button><i class="fa fa-print"></i></button>
                  </div>
                  </div>
          </div>
      </div>
    </div>
  </div>
</div>
