<div class="row">
        <div class="col-lg-8 col-md-6">
		<ul class="nav nav-tabs">
			
			<li role="presentation" ><a href="<?php echo  BASE_URL ?>almacen/clasificacion/index/">Clasificaciones</a></li>
			<li role="presentation"  ><a href="<?php echo  BASE_URL ?>almacen/grupo/index/">Grupos</a></li>
			<li role="presentation" class="active"><a href="#">Presentaciones</a></li>
			<li role="presentation"><a href="<?php echo  BASE_URL ?>almacen/marca/index/">Marcas</a></li>
			<li role="presentation"><a href="<?php echo  BASE_URL ?>configuracion/unidadmedida/index/">Unidad Medida</a></li>			
		</ul>
        <div class="panel panel-default">
        <div class="">
        <nav class="navbar navbar-default">
            <div class="container-fluid">
                <div class="navbar-header navbar-btn">
                    <a > <button class="nuevo btn btn-default" title="Presione aquí para AGREGAR un nuevo registro" value="" ><i  class="fa fa-plus"></i></button> </a>
                    <a  target="_blank" href="<?php echo BASE_URL ?>reporte/index/catPresentacionProd/" title="Imprimir Catálogo"><button class="btn btn-default"><i class="fa fa-print"></i></button></a>
                </div>  
                <form class="navbar-form navbar-right" role="search" action="" method="post">
                    <div class="form-group">
                        <input type="text" maxlength="100" name="busqueda" class="form-control alfa_desc" placeholder="Filtrar nombre">
                    </div>
                    <button type="submit" class="btn btn-default"><i  class="fa fa-search" > Buscar</i></button>
                </form>    
            </div>
        </nav>
            </div>
        
          <div class="panel-body">
            <div class="table-responsive">
                <table class="table table-bordered">
                    <thead>
                    <tr class="bg-light-blue-active">                        
                        <th>Nombre</th>
                        <th>Contenido X Presentación</th>                        
                        <th>Contenido X Unidad</th>
                        <th></th>
                        <th></th>
                        <th></th>
                    </tr>
                    </thead>
                    <tbody>
                    <?php $i = 1; ?>    
                    <?php if(isset($this->lista) && count($this->lista)) :?>
                        <?php foreach ($this->lista as $val) :?>
                        <tr>
                            <td><?php echo ucwords($val['nombre_presentacion']) ?></td>
                            <td><?php echo ucwords($val['cantidad_presentacion']) ?></td>                            							
                            <td><?php echo $val['cantidad_uni_med'].' '.ucwords($val['medida']) ?></td>
                            <td>
                                <?php if($val['estatus_presentacion']==1): ?>
                                <button class="editar btn btn-default" title="Presione aquí para EDITAR" value="<?php echo $val['id_presentacion'] ?>" ><i  class="fa fa-pencil-square-o"></i></button>
                                <?php endif; ?>
                            </td>
                            <td>
                                <?php if($val['estatus_presentacion']==1): ?>
                                <button class="eliminar btn btn-default" title="Presione aquí para ELIMINAR" value="<?php echo $val['id_presentacion'] ?>"><i class="fa fa-trash-o"></i></button>
                                <?php endif; ?>
                            </td>
                            <td>
                                <?php if($val['estatus_presentacion']==9): ?>
                                <button class="restaurar btn btn-default" title="Presione aquí para RESTAURAR" value="<?php echo $val['id_presentacion'] ?>"><i class="fa fa-recycle"></i></button>
                                <?php endif; ?>
                            </td>
                        </tr>
                        <?php $i++; ?>
                        <?php endforeach; ?>
                    <?php endif; ?>    
                    </tbody>
                </table>
                
            </div>
          </div>
		  <div class="panel-footer" >
            <p>
                <?php if(isset($this->paginacion)) echo $this->paginacion; ?>
            </p>
    	  </div>	
        </div>
    </div>
    <div class="col-lg-4 col-md-6">
        <div class="panel panel-default">
            <div class="panel-heading">Gestión de Presentación para Producto</div>
            <div class="panel-body">
                <form name="form_presentacion" id="form_presentacion" method="post" autocomplete="off" action="<?php echo BASE_URL ?>almacen/presentacion/agregar/">
                    <input name="guardar" type="hidden" value="1" id="guardar">
                    <input name="id" type="hidden" value="0" id="id">
                    <input name="aux" type="hidden" value="0" id="aux">
                    <div class="form-group">
                      <label>*Nombre:</label>
                      <input name="descripcion" disabled="disabled" maxlength="100" type="text" class="form-control alfa_desc" id="descripcion" placeholder="Ingrese nombre de la presentación" required >
                    </div>
                    <div class="form-group">
                      <label>*Contenido por Presentación:</label>
                      <input name="unidades" id="unidades" disabled="disabled" maxlength="6" type="text" class="form-control num_real" placeholder="Ingrese la Cantidad por Presentación" required >
                    </div>
                    <div class="form-group">
                      <label>*Contenido por Unidad:</label>
                      <input name="cantidad" id="cantidad" disabled="disabled" maxlength="6" type="text" class="form-control num_real" placeholder="Ingrese la Cantidad por Unidad" required >
                    </div>
                    <div class="form-group">
                      <label>*Unidad de Medida:</label>
                      <select name="medida" disabled="disabled" id="medida" class="form-control" required >
                          <option value="0">-Seleccione-</option>
                          <?php if(isset($this->medida) && count($this->medida)): ?>
                                <?php foreach ($this->medida as $val): ?>
                                    <?php if($val['estatus_uni_med']==1): ?>
                                    <option value="<?php echo $val['id_uni_med']  ?>"><?php echo $val['nombre_uni_med']  ?></option>   
                                    <?php endif; ?>    
                                <?php endforeach; ?>
                          <?php endif; ?>
                      </select>
                    </div>
                    <button type="button" disabled="disabled" name="agregar" id="agregar" title="Presione aquí para GUARDAR el registro"  class="btn btn-primary"> <i class="fa fa-floppy-o"></i> Guardar</button>
                    <button type="button" disabled="disabled" name="cancelar" title="Presione aquí para CANCELAR el registro" id="cancelar" class="btn btn-danger"> <i class="fa fa-undo"></i> Cancelar</button>
                </form>    
            </div>
        </div>
    </div>    
</div>