<div class="row">
	<div class="col-lg-12 col-md-6">
	<form name="frm-auto" method="post" action="">
	<input name="guardar" type="hidden" value="1" />
	<input name="compra" type="hidden" value="<?php echo $this->nro_compra ?>"/>
     <div class="panel panel-default">    
        <nav class="navbar navbar-default">
            <div class="container-fluid">
                  
                    
            </div>
        </nav>            
        <div class="panel-body">
		<?php $i=0; ?>
		<?php if(isset($this->gasto) && count($this->gasto)) :?>
			<?php foreach ($this->gasto as $val) :?>
			<div class="panel panel-default">
				<div class="panel-heading">
					<label><input name="gasto[]" type="checkbox"  value="<?php echo $val['maestro']['id_gasto'] ?>" /> Nro Factura : <?php echo $val['maestro']['nro_doc_ori'].' | Fecha:'.date('d-m-Y',strtotime($val['maestro']['fecha_emision_gasto']))  ?> &nbsp;  | &nbsp; Proveedor : <?php echo $val['maestro']['razon_social_proveedor'] ?>  &nbsp;   | &nbsp;  Total : <?php echo $val['maestro']['total'] ?> </label>
					<input name="tipo_documento[]" type="hidden" value="<?php echo $val['maestro']['tipo_doc_ori'] ?>" /><input name="nro_documento[]" type="hidden" value="<?php echo $val['maestro']['nro_doc_ori'] ?>" />
				</div>
				<div class="table-responsive">
					<table class="table table-bordered">
						<thead>
						<tr class="cabecera-gris">
							<th>Código</th>
							<th>Nombre</th>
							<th>Costo</th>        
							<th>Cant.</th>
							<th>Monto</th>
							<th>Tsa. Iva</th>
							<th>Total</th>
							<th>Distribucion</th>
							
						</tr>
						</thead>
						 <tbody>
						<?php if(isset($val['detalle']) && count($val['detalle'])) :?>
							<?php 
									$mto_dist=0;
									$por_dist=0;
									$i = 0;
									if(count($val['detalle'])> 1 ){
										$mto_dist = $val['maestro']['total']/ count($val['detalle']);
										$por_dist = ($mto_dist * 100) / $val['maestro']['total']; }  
									else {
										$mto_dist = $val['maestro']['total'];
										$por_dist = 100;
									}
									$nro_detalle = count($val['detalle']);
							?>
							
							<?php foreach ($val['detalle'] as $det) :?>
								
							<tr>
								<td class="text-right"><?php echo $det['id_det_compra'] ?></td>
								<td><?php echo $det['nombre_producto'] ?><input name="producto[]" type="hidden" value="<?php echo $det['det_producto_id'] ?>" /></td>
								<td><?php echo $det['costo_producto']; ?></td>
								<td><?php echo $det['cantidad_producto'] ?><input name="cantidad_producto[]" type="hidden" value="<?php echo $det['cantidad_producto'] ?>" /></td>
								<td class="text-right"><span class="text-right"><?php echo $det['monto_producto'] ?></span></td>
								<td class="text-right"><span class="text-right"><?php echo $det['tsa_iva_producto'] ?></span></td>
								<td class="text-right"><span class="text-right"><?php echo $det['mto_total_producto'] ?></span></td>
								<td class="text-right"><input name="porcentaje[]" id="porcentaje" type="text" class="form-control text-right inline" size="3" value="<?php echo $por_dist ?>" /><span class="text-right">%</span></td>
								<td class="text-right"><input name="distribucion[]" id="distribucion" type="text" class="form-control text-right inline" size="10" value="<?php echo $mto_dist ?>" readonly="true" />Bs</td>
							</tr>
							<?php $i++; ?>		
							<?php endforeach; ?>
						<?php endif; ?>
						</tbody>
					</table>
				</div>	
			</div>
			<?php endforeach; ?>
        <?php endif; ?>   
		
      </div>
	 
    </div>	
	 <div class="form-inline ">
		<a href="<?php echo BASE_URL ?>compra/compras/index/" title="Cancelar"><button type="button" class="form-control btn-danger"><i class="fa fa-undo"></i> Cancelar</button></a>
		<button type="submit" class="form-control btn-primary" title="Guardar"><i class="fa fa-check-square-o"></i> Autorizar Asignación de Productos</button>
		<input name="ndetalle" type="hidden" value="<?php echo $nro_detalle; ?>"  />
	</div>
  
 </form>
 </div> 
</div>

<div class="modal fade bs-example-modal-lg" tabindex="-1" role="dialog" aria-labelledby="myLargeModalLabel">
  <div class="modal-dialog modal-lg">
    <div class="modal-content">
      <div class="modal-header cabecera-gris">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
		<h3>Requisición de Productos</h3>
      </div>
      <div class="modal-body">
          <div class="panel-default">
              <div class="panel-body">
                <div class="form-group col-md-3">
                    <label>Nro de Requisición</label>
                    <input name="nro" id="nro" type="text" class="form-control " value="" />
                </div>
                <div class="form-group col-md-3">
                    <label>Fecha</label>
                    <input name="fecha" id="fecha" type="text" class="form-control" value="" />
                </div>
                <div class="form-group col-md-5">
                    <label>Depósito</label>
                    <input name="proveedor" id="proveedor" type="text" class="form-control" value="" />
                </div>
              </div>    
          </div>
          <div class="panel-default">
              <div class="panel-body">
                    <div id="tabla-detalle">
                        <div class="table-responsive">
                          <table class="table table-bordered" id="tabla">
                              <thead>
                                  <tr class="cabecera-gris" >
                                      <th width='150'>Código</th>
                                      <th width='400'>Descripción</th>
                                      <th width='150'>Marca</th>
                                      <th width='250'>Modelo</th>
                                      <th width='100'>Cantidad</th>
                                      <th></th>
                                  </tr>
                              </thead>
                              <tbody>

                              </tbody>
                          </table>
                      </div>
                    </div>
					<hr>
                  <div>
                      <a href="<?php echo BASE_URL ?>reporte/index/print_Requisicion/<?php echo '1' ?>"><button><i class="fa fa-print"></i></button></a>
                  </div>
                  </div>
          </div>
      </div>    
    </div>
  </div>
</div>