<div class="row">
    <div class="col-lg-12 col-md-6">
        <div class="panel panel-default">

            <div class="">
                <nav class="navbar navbar-default">
                    <div class="container-fluid">
                        <div class="navbar-header navbar-btn">
                            <a class="" href="<?php echo BASE_URL ?>configuracion/deposito/agregar/"> <button class="btn btn-default" title="Presione aquí para AGREGAR un nuevo registro" value="" ><i  class="fa fa-plus"></i></button> </a>
                            <a class="" target="_blank" href="<?php echo BASE_URL ?>reporte/index/catDeposito/" title="Imprimir Catálogo"><button class="btn btn-default"><i class="fa fa-print"></i></button></a>
                        </div>
                        <form class="navbar-form navbar-right" role="search" action="" method="post">
                            <label>Unidad Operativa</label>
                            <select class="form-control" name="unidad" id="unidad" required />
                            <option value="-">-TODOS-</option>
                            <?php if(isset($this->unidad)&& count($this->unidad)): ?>
                                    <?php foreach ($this->unidad as $val): ?>
                                    <option value="<?php echo $val['id_unidad_operativa'] ?>"><?php echo strtoupper($val['nombre_unidad_operativa']) ?> </option>
                                    <?php endforeach; ?>
                            <?php endif; ?>
                            </select>
                            <div class="form-group">
                                <input type="text" name="busqueda" class="form-control alfa_desc" placeholder="Filtrar nombre">
                            </div>
                            <button type="submit" class="btn btn-default"><i  class="fa fa-search" ></i></button>
                        </form>
                    </div>
                </nav>
            </div>

          <div class="panel-body">
            <div class="table-responsive">
                <table class="table table-bordered">
                    <thead>
                    <tr class="bg-light-blue-active">
                        <th>Código</th>
                        <th>Nombre</th>
                        <th>Tipo de Depósito</th>
                        <th>Ubicación</th>
                        <th>Teléfono</th>
                        <th width="30"></th>
                        <th width="30"></th>
                        <th width="30"></th>
                    </tr>
                    </thead>
                    <tbody>
                    <?php if(isset($this->lista) && count($this->lista)) :?>
                        <?php foreach ($this->lista as $val) :?>
                        <tr>
                            <td><?php echo $val['id_deposito'] ?></td>
                            <td><?php echo ucwords($val['nombre_deposito']) ?></td>
                            <td><?php echo ucwords($val['tipo']) ?></td>
                            <td><?php echo ucwords($val['ubicacion_deposito']) ?></td>
                            <td><?php echo $val['telefono_deposito'] ?></td>
                            <td>
                                <?php if($val['estatus_deposito']==1): ?>
                                <a href="<?php echo BASE_URL ?>almacen/deposito/editar/<?php echo $val['id_deposito'] ?>" >
                                <button class="editar btn btn-default" title="Presione aquí para EDITAR" value="<?php echo $val['id_deposito'] ?>" ><i  class="fa fa-pencil-square-o"></i></button>
                                <?php endif; ?>
                            </td>
                            <td>
                                <?php if($val['estatus_deposito']==1): ?>
				<button class="eliminar btn btn-default" title="Presione aquí para ELIMINAR" value="<?php echo $val['id_deposito'] ?>" ><i  class="fa fa-trash-o"></i></button>
                                <?php else: ?>
				<button class="restaurar btn btn-default" title="Presione aquí para RESTAURAR" value="<?php echo $val['id_deposito'] ?>" ><i  class="fa fa-recycle"></i></button>
				<?php endif; ?>
                            </td>
                            <td>
                                <a href="<?php echo BASE_URL ?>almacen/deposito/trabajadorDeposito/<?php echo $val['id_deposito'] ?>" >
                                    <button class="btn btn-default" title="Presione aquí para ver Usuarios Asignados "><i class="fa fa-inbox"></i></button>
                            </td>
                        </tr>
                        <?php endforeach; ?>
                    <?php endif; ?>
                    </tbody>
                </table>
                <hr>
                <p>
                        <?php if(isset($this->paginacion)) echo $this->paginacion; ?>
                </p>
            </div>
          </div>

        </div>
    </div>

</div>
