<div class="row">
        <div class="col-lg-8 col-md-6"> 
		<ul class="nav nav-tabs">
			<li role="presentation" ><a href="<?php echo  BASE_URL ?>almacen/producto/index/"><i  class="fa fa-cube"></i> Productos</a></li>
			<li role="presentation" class="active" ><a href="<?php echo  BASE_URL ?>archivo/servicio/index/"><i  class="fa  fa-wrench"></i> Servicios</a></li>				
		</ul>	
        <div class="panel panel-default">
        <div class="">
            <nav class="navbar navbar-default">
                <div class="container-fluid">
                    <div class="navbar-header navbar-btn">
                        <a class=""> <button class="btn btn-default nuevo" title="Presione aquí para AGREGAR un nuevo registro" value="" ><i  class="fa fa-plus"></i></button> </a>
                        <a class="" target="_blank" href="<?php echo BASE_URL ?>reporte/index/catRubrosProd/" title="Imprimir Catálogo"><button class="btn btn-default"><i class="fa fa-print"></i></button></a>
                    </div>  
                    
                    <form class="navbar-form navbar-right" role="search" action="" method="post">
                        <div class="form-group">
                            <input type="text" maxlength="100" name="busqueda" class="form-control alfa_desc" placeholder="Filtrar nombre">
                        </div>
                        <button type="submit" class="btn btn-default"><i  class="fa fa-search" > Buscar</i></button>
                    </form>    
                </div>
            </nav>
        </div>
          <div class="panel-body">
            <div class="table-responsive">
                <table class="table table-bordered">
                    <thead>
                    <tr class="cabecera-gris">
                        <th width="60">Código</th>
                        
						<th>Clasificacion</th>
						<th>Grupo</th>
						<th>Nombre</th>
                        
                        <th width="20"></th>
                        <th	width="20"></th>
                    </tr>
                    </thead>
                    <tbody>
                    <?php $i = 1; ?>    
                    <?php if(isset($this->lista) && count($this->lista)) :?>
                        <?php foreach ($this->lista as $val) :?>
                        <tr >
                            <td><?php echo $val['id_servicio'] ?></td>
							<td><?php echo $val['nombre_clasificacion'] ?></td>
							<td><?php echo $val['nombre_grupo'] ?></td>
							
                            <td><?php echo strtoupper($val['nombre_servicio']) ?></td>
                            
                            
                            <td>
                                <?php if($val['estatus_servicio']==1): ?>
                                <button class="editar btn btn-default" title="Presione aquí para EDITAR" value="<?php echo $val['id_servicio'] ?>" ><i  class="fa fa-pencil-square-o"></i></button>
                                <?php endif; ?>
                            </td>    
                            <td>
                                <?php if($val['estatus_servicio']==1): ?>
                                <button class="eliminar btn btn-default" title="Presione aquí para ELIMINAR" value="<?php echo $val['id_servicio'] ?>"><i class="fa fa-trash-o"></i></button>
								<?php else:  ?>
									<?php if($val['estatus_servicio']==9): ?>
										<button class="restaurar btn btn-default" title="Presione aquí para RESTAURAR" value="<?php echo $val['id_servicio'] ?>"><i class="fa fa-recycle"></i></button>									
									<?php endif; ?>
								<?php endif; ?>
                            </td>
                            
                        </tr>
                        <?php $i++; ?>
                        <?php endforeach; ?>
                    <?php endif; ?>    
                    </tbody>
                </table>
                
            </div>
          </div>
		  <div class="panel-footer" >
            <p>
                <?php if(isset($this->paginacion)) echo $this->paginacion; ?>
            </p>
    	  </div>	
        </div>
    </div>
    <div class="col-lg-4 col-md-6">
        <div class="panel panel-default">
            <div class="panel-heading">Gestión  de   Impuesto  </div>
            <div class="panel-body">
                <form name="form_servicio" id="form_servicio" method="post" autocomplete="off" action="<?php echo BASE_URL ?>archivo/servicio/agregar/">
                    <input name="guardar" type="hidden" value="1" id="guardar">
                    <input name="id" type="hidden" value="0" id="id">
                    <input name="aux" type="hidden" value="" id="aux">
                    <div class="form-group">
                      <label>*Clasificacion:</label>
                      <select name="clasificacion" disabled="disabled" class="form-control " id="clasificacion" required  >
						<option value="">-SELECCIONE-</option>
						<?php if(isset($this->clasificacion)): ?>
						<?php foreach($this->clasificacion as $val): ?>
							<option value="<?php echo $val['id_clasificacion'] ?>"><?php echo $val['nombre_clasificacion'] ?></option>						
						<?php endforeach;?>
						<?php endif;?>
					  </select>
                    </div>
					<div class="form-group">
                      <label>*Grupo:</label>
                      <select name="grupo" disabled="disabled" class="form-control " id="grupo" required  >
						<option value="">-SELECCIONE-</option>
					  </select>
                    </div>
					<div class="form-group">
                      <label>*Nombre:</label>
                      <input name="nombre" disabled="disabled" maxlength="100" type="text" class="form-control alfa_desc" id="nombre" required placeholder="Ingrese nombre " >
                    </div>
                    <div class="form-group">
                      <label>Comentario:</label>
                      <textarea name="comentario" disabled="disabled" maxlength="150" cols="1" rows="2" type="text" multiple="1" class="form-control alfa_desc" id="comentario"  placeholder="Ingrese una condicion"></textarea>
                    </div>
                    <button type="button" disabled="disabled" name="agregar" id="agregar" title="Presione aquí para GUARDAR el registro"  class="btn btn-primary"> <i class="fa fa-floppy-o"></i> Guardar</button>
                    <button type="button" disabled="disabled" name="cancelar" title="Presione aquí para CANCELAR el registro" id="cancelar" class="btn btn-danger"> <i class="fa fa-undo"></i> Cancelar</button>
                </form>    
            </div>
        </div>
    </div>    
</div>